### ISSUE TITLE
<future>: std::this_thread::sleep_for deadlock when executed via std::async(std::launch::async, ...)

### ISSUE THREAD

**Issue by Yen** [microsoft/STL#1012] opened 2020-07-07 23:15 UTC
Reproducible case (debug x64) (can take an hour or so before deadlock occurs on my machine):

```cpp
int main(int argc, char* argv[]) {
	std::async(std::launch::async, [] {
		std::cout.sync_with_stdio(false);
		while (true) {
			std::cout << std::chrono::high_resolution_clock::now().time_since_epoch().count() << std::endl;
			std::this_thread::sleep_for(std::chrono::milliseconds(1));
		}
	});
}
```

Full callstack for reference on **deadlocked** thread:
![image](https://user-images.githubusercontent.com/10085851/86854270-02aeab00-c0b0-11ea-943a-98b46cabc683.png)

Microsoft Visual Studio Professional 2019 Preview
Version 16.7.0 Preview 3.1

**Comment by statementreply** [comment] 2020-07-08 02:04
Possibly caused by #971?

**Comment by StephanTLavavej** [comment] 2020-07-08 21:02
We're porting the fix for #971 to VS 2019 16.7 Preview 5, so we should wait for that release and then confirm that this no longer reproduces. Thanks for reporting it so quickly! :smile_cat:

**Comment by CaseyCarter** [comment] 2020-07-08 23:26
FWIW, I've been running versions of this repro built with 16.7p3.1 and with trunk STL headers for about 8 hours now. The 16.7p3.1 version deadlocked in about 45 minutes, and the trunk version is still going, so it looks like #971 is in fact the cause.

**Comment by StephanTLavavej** [comment] 2020-07-09 09:41
Thanks, @CaseyCarter! I think that's enough evidence for us to close this issue as a duplicate that has been fixed. @Yen, feel free to reopen this if you see it happening again with 16.7 Preview 5 or later.

**Closed by StephanTLavavej** 2020-07-09 09:41 UTC
Labels: bug, duplicate

**Comment by CaseyCarter** [comment] 2020-07-10 13:31
> Thanks, @CaseyCarter! I think that's enough evidence for us to close this issue as a duplicate that has been fixed.

FYI, the version with the fix is still running ;)
