### ISSUE TITLE
Investigate properly designing `_CONTAINER_DEBUG_LEVEL`

### ISSUE THREAD

**Issue by Predelnik** [microsoft/STL#586] opened 2020-03-04 14:02 UTC
This is not an issue per se but from viewpoint of the users who disabled `_ITERATOR_DEBUG_LEVEL` in debug due to the way it affects parallel performance, more lightweight `_CONTAINER_DEBUG_LEVEL` seems to be very useful, providing just simple bounds checking etc. However I see that it's not documented as well as [_ITERATOR_DEBUG_LEVEL](https://docs.microsoft.com/en-us/cpp/standard-library/iterator-debug-level?view=vs-2019) and I wonder if defining it is a public, official feature and thus it's okay to use it or is it for internal use only? Also it'd be nice to see the scope of checks enabling it performs without looking at sources of course.

Feel free to close if I should create an issue somewhere like in https://github.com/MicrosoftDocs/cpp-docs about this instead.

**Comment by StephanTLavavej** [comment] 2020-03-04 21:33
Marking as `decision needed` because we're not really comfortable with the design and behavior of the feature, so we need a plan here.

**Comment by jdashg** [comment] 2021-12-27 22:03
We are hoping to enable `_CONTAINER_DEBUG_LEVEL=1` in Firefox, so I really hope we can rely on its functionality!
https://bugzilla.mozilla.org/show_bug.cgi?id=1746547

**Comment by StephanTLavavej** [comment] 2023-04-26 21:35
We talked about this at the weekly maintainer meeting and decided that we're not comfortable enough with the (lack of) design of this feature to begin documenting it for wide usage.

We'll change this issue accordingly. This may be something we'll need to consider for vNext since it could have wide-reaching effects.

**Comment by StephanTLavavej** [comment] 2024-11-20 22:12
Closing as a duplicate of the newer issue #5090.

**Closed by StephanTLavavej** 2024-11-20 22:12 UTC
Labels: duplicate, enhancement
