### ISSUE TITLE
<memory> should use concepts instead of return-type SFINAE

### ISSUE THREAD

**Issue by mnatsuhara** [microsoft/STL#1367] opened 2020-10-13 17:52 UTC
The `friend` functions for `shared_ptr` and `unique_ptr` are the only places where we still use return-type SFINAE.  We should update those functions to be concept-constrained and remove this return-type SFINAE once concepts are fully supported by EDG.  

https://github.com/microsoft/STL/blob/e7d5113376763268075d87dbad662a7cf4763a10/stl/inc/memory#L1904-L1937

**Comment by AdamBucior** [comment] 2020-10-13 18:22
Isn't it a duplicate of #602?

**Closed** 2020-10-14 21:26 UTC
Labels: duplicate, enhancement
