### ISSUE TITLE
xlocnum error C2065: 'PTRDIFF_MAX': undeclared identifier

### ISSUE THREAD

**Issue by daironxuan** [microsoft/STL#4843] opened 2024-07-17 09:53 UTC
# error C2065: 'PTRDIFF_MAX': undeclared identifier

# The specific code is:

```c++
for (size_t _Idx; _First != _Last && (_Idx = _STD _Find_elem(_Atoms, *_First)) < _Offset_dec_digit_end;
                     _Seendigit = true, (void) ++_First) {
                    if (_Exponent_part < PTRDIFF_MAX / 10
                        || (_Exponent_part == PTRDIFF_MAX / 10
                            && static_cast<ptrdiff_t>(_Idx) <= PTRDIFF_MAX % 10)) { // save a significant exponent digit
                        _Exponent_part = _Exponent_part * 10 + static_cast<ptrdiff_t>(_Idx);
                    } else {
                        _Exponent_part = PTRDIFF_MAX; // saturated
                    }
                }
```

**Comment by daironxuan** [comment] 2024-07-17 09:54
Visual2022_IDE\VC\Tools\MSVC\14.40.33807\include\xlocnum(1031): error C2065: “PTRDIFF_MAX”: undeclared identifier

**Comment by daironxuan** [comment] 2024-07-17 10:08
This error will occur as long as the iostream header file is added

**Comment by frederick-vs-ja** [comment] 2024-07-17 10:16
Could you paste a minimal program which causes this error?

**Comment by cpplearner** [comment] 2024-07-17 10:59
Yeah we need a minimal reproducible example.

**Comment by daironxuan** [comment] 2024-07-17 12:31
> 现

# I seem to have discovered something wrong!

I don't have this problem using Visual Studio 2019, but I get the following error with Visual Studio 2022:

**Comment by daironxuan** [comment] 2024-07-17 12:32
What seems to result is a project with C within the C++ project, but I'm not quite sure, I will make a repository project public, the first one is

**Comment by daironxuan** [comment] 2024-07-17 12:36
切换成Visual Studio 2022之后完整错误如下：

====================[ 构建 | all | Debug ]========================================
D:\apps\IDEA\app\CLion\bin\cmake\win\x64\bin\cmake.exe --build C:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\cmake-build-debug --target all -j 30
[1/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\osal\win32\osal.c.obj
[2/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\oshw\win32\nicdrv.c.obj
[3/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatbase.c.obj
[4/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatfoe.c.obj
[5/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatprint.c.obj
[6/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatcoe.c.obj
[7/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatsoe.c.obj
[8/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatmain.c.obj
[9/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\oshw\win32\oshw.c.obj
[10/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercateoe.c.obj
[11/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatdc.c.obj
[12/15] Building C object CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatconfig.c.obj
[13/15] Building CXX object CMakeFiles\Motion.dir\native_interface.cpp.obj
FAILED: CMakeFiles/Motion.dir/native_interface.cpp.obj 
FAILED: CMakeFiles/Motion.dir/native_interface.cpp.obj
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\bin\Hostx64\x64\cl.exe /nologo /TP -DMotion_EXPORTS -D_XKEYCHECK_H -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\ src\Lib\EtherCAT\oshw\win32 -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\Lib\EtherCAT\osal -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\ Lib\EtherCAT\osal\win32 -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\Lib\EtherCAT\soem -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\Lib\ EtherCAT\oshw\win32\wpcap\Include /DWIN32 /D_WINDOWS /EHsc /Ob0 /Od /RTC1 -std:c++17 -MDd -Zi /wd4819 /wd4068 /showIncludes /FoCMakeFiles\Motion.dir\native_interface.cpp.obj /FdCMakeFiles\Motion.dir\ /FS -c C:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\native_interface.cpp
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1028): error C2065: 'PTRDIFF_MAX': undeclared identifier
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1028): note: The template instantiation context (the earliest instantiation context) is
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1662): note: Check the instantiation of the class template being compiled "std::num_get<wchar_t,std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t>>>" reference
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(589): note: When compiling class template member function "_InIt std::num_get<wchar_t,_InIt>::do_get(_InIt,_InIt ,std::ios_base &,std::ios_base::iostate &,double &) const”
        with
        [
            _InIt=std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t>>
        ]
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(623): note: See "std::num_get<wchar_t,std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t> The first reference to "std::num_get<wchar_t,std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t>>>::do_get" in >>::do_get"
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(594): note: View the instantiation of the function template being compiled "std::_Num_get_parse_result std::num_get<wchar_t,std:: istreambuf_iterator<wchar_t,std::char_traits<wchar_t>>>::_Parse_fp_with_locale<0>(char *const,const int,_InIt &,_InIt &,const std::locale &)"
        with
        [
            _InIt=std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t>>
        ]
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1029): error C2065: 'PTRDIFF_MAX': undeclared identifier
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1030): error C2065: 'PTRDIFF_MAX': undeclared identifier
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1033): error C2065: 'PTRDIFF_MAX': undeclared identifier
[14/15] Building CXX object CMakeFiles\Motion.dir\src\Controller\Master\driver.cpp.obj
FAILED: CMakeFiles/Motion.dir/src/Controller/Master/driver.cpp.obj
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\bin\Hostx64\x64\cl.exe /nologo /TP -DMotion_EXPORTS -D_XKEYCHECK_H -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\ src\Lib\EtherCAT\oshw\win32 -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\Lib\EtherCAT\osal -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\ Lib\EtherCAT\osal\win32 -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\Lib\EtherCAT\soem -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\Lib\ EtherCAT\oshw\win32\wpcap\Include /DWIN32 /D_WINDOWS /EHsc /Ob0 /Od /RTC1 -std:c++17 -MDd -Zi /wd4819 /wd4068 /showIncludes /FoCMakeFiles\Motion.dir\src\Controller\Master \driver.cpp.obj /FdCMakeFiles\Motion.dir\ /FS -c C:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\Controller\Master\driver.cpp
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1028): error C2065: 'PTRDIFF_MAX': undeclared identifier
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1028): note: The template instantiation context (the earliest instantiation context) is
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1662): note: Check the instantiation of the class template being compiled "std::num_get<wchar_t,std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t>>>" reference
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(589): note: When compiling class template member function "_InIt std::num_get<wchar_t,_InIt>::do_get(_InIt,_InIt ,std::ios_base &,std::ios_base::iostate &,double &) const”
        with
        [
            _InIt=std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t>>
        ]

**Comment by daironxuan** [comment] 2024-07-17 12:37
> 切换成Visual Studio 2022之后完整错误如下：
> 
> ====================[ 构建 |全部 |调试]========================================== D:\apps\IDEA\app \CLion\bin\cmake\win\x64\bin\cmake.exe --build C:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\cmake-build-debug --target all -j 30 [1/15 ] 构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\osal\win32\osal.c.obj [2/15] 构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\oshw\win32\nicdrv .c.obj [3/15] 构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatbase.c.obj [4/15]构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatfoe.c.obj [5/15] 构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatprint.c.obj [ 6/15] 构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatcoe.c.obj [7/15] 构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatsoe。 c.obj [8/15] 构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatmain.c.obj [9/15] 构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\ oshw\win32\oshw.c.obj [10/15] 构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercateoe.c.obj [11/15] 构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatdc .c.obj [12/15] 构建 C 对象 CMakeFiles\Motion.dir\src\Lib\EtherCAT\soem\ethercatconfig.c.obj [13/15] 构建 CXX 对象 CMakeFiles\Motion.dir\native_interface.cpp.obj 失败：CMakeFiles/Motion.dir/native_interface.cpp.obj 失败：CMakeFiles/Motion.dir/native_interface.cpp.obj D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\bin\Hostx64\x64\cl.exe /nologo /TP -DMotion_EXPORTS -D_XKEYCHECK_H -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\ src\Lib\EtherCAT\oshw\win32-IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\Lib\EtherCAT\osal-IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\ Lib\EtherCAT\osal\win32-IC:\用户\Lenvo\桌面\项目\EtherCAT\Motion\src\Lib\EtherCAT\soem-IC:\用户\Lenvo\桌面\项目\EtherCAT\Motion\src\Lib\ EtherCAT\oshw\win32\wpcap\Include /DWIN32 /D_WINDOWS /EHsc /Ob0 /Od /RTC1 -std:c++17 -MDd -Zi /wd4819 /wd4068 /showIncludes /FoCMakeFiles\Motion.dir\native_interface.cpp.obj /FdCMakeFiles\Motion.dir\ /FS -c C:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\native_interface.cpp D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum( 1028)：错误 C2065：‘PTRDIFF_MAX’：未声明的标识符 D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1028):注意：模板实例化上下文（最早的实例化上下文）为 D:\apps\Visual2022_IDE\VC\Tools\MSVC\ 14.41.34021\include\xlocnum(1662): 注意：检查正在编译的类模板的实例化“std::num_get<wchar_t,std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t>>>”参考 D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(589): 注意：在编译类模板成员函数“_InIt std::num_get<wchar_t,_InIt>::do_get(_InIt,_InIt ,std::ios_base &,std::ios_base::iostate &,double &) const”标签的时 ，请使用 [ _InIt=std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t>> ] D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(623): 注意：参见“std::num_get<wchar_t,std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t> >>::do_get”中第一次引用“std::num_get<wchar_t,std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t>>>::do_get” D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(594): 注意：查看正在编译的函数模板的实例化“std::_Num_get_parse_result std::num_get<wchar_t,std:: istreambuf_iterator<wchar_t,std::char_traits<wchar_t>>>::_Parse_fp_with_locale<0>(char *const,const int,_InIt &,_InIt &,const std::locale &)" 标签的，请使用 [ _InIt=std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t>> ] D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1029): error C2065: ‘PTRDIFF_MAX’: 未声明的标识符 D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1030): error C2065: ‘PTRDIFF_MAX’: 未声明的标识符 D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1033): 错误 C2065: “PTRDIFF_MAX”: 未声明的标识符 [14/15] 构建 CXX 对象 CMakeFiles\Motion.dir\src\Controller\Master\driver.cpp.obj 失败: CMakeFiles/Motion.dir/src/Controller/Master/driver.cpp.obj D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\bin\Hostx64\x64\cl.exe /nologo /TP -DMotion_EXPORTS -D_XKEYCHECK_H -IC:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\ src\Lib\EtherCAT\oshw\win32 -IC:\用户\Lenvo\桌面\项目\EtherCAT\Motion\src\Lib\EtherCAT\osal -IC:\用户\Lenvo\桌面\项目\EtherCAT\Motion\src\ Lib\EtherCAT\osal\win32 -IC:\用户\Lenvo\桌面\项目\EtherCAT\Motion\src\Lib\EtherCAT\soem -IC:\用户\Lenvo\桌面\项目\EtherCAT\Motion\src\Lib\ EtherCAT\oshw\win32\wpcap\Include /DWIN32 /D_WINDOWS /EHsc /Ob0 /Od /RTC1 -std:c++17 -MDd -Zi /wd4819 /wd4068 /showIncludes /FoCMakeFiles\Motion.dir\src\Controller\Master \driver.cpp.obj /FdCMakeFiles\Motion.dir\ /FS -c C:\Users\Lenvo\Desktop\Project\EtherCAT\Motion\src\Controller\Master\driver.cpp D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1028): error C2065: 'PTRDIFF_MAX': 未声明的标识符 D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1028): 注意：模板实例化上下文（最早的实例化上下文）是 D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1662): 注意：检查正在编译的类模板的实例化“std::num_get<wchar_t,std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t>>>”引用 D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(589): 注意：在编译类模板成员函数“_InIt std::num_get<wchar_t,_InIt>::do_get(_InIt,_InIt ,std::ios_base &,std::ios_base::iostate &,double &) const” 标签的，请使用 [ _InIt=std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t>> ]


D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(623): note: See "std::num_get<wchar_t,std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t> The first reference to "std::num_get<wchar_t,std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t>>>::do_get" in >>::do_get"
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(594): note: View the instantiation of the function template being compiled "std::_Num_get_parse_result std::num_get<wchar_t,std:: istreambuf_iterator<wchar_t,std::char_traits<wchar_t>>>::_Parse_fp_with_locale<0>(char *const,const int,_InIt &,_InIt &,const std::locale &)"
        with
        [
            _InIt=std::istreambuf_iterator<wchar_t,std::char_traits<wchar_t>>
        ]
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1029): error C2065: 'PTRDIFF_MAX': undeclared identifier
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1030): error C2065: 'PTRDIFF_MAX': undeclared identifier
D:\apps\Visual2022_IDE\VC\Tools\MSVC\14.41.34021\include\xlocnum(1033): error C2065: 'PTRDIFF_MAX': undeclared identifier

**Comment by daironxuan** [comment] 2024-07-17 12:39
[build error log.txt](https://github.com/user-attachments/files/16265667/build.error.log.txt)

**Comment by StephanTLavavej** [comment] 2024-07-17 21:20
Thanks for reporting this issue. I'm resolving it as invalid because your repo contains a file named `stdint.h` and your `/I` compiler options are causing `#include <stdint.h>` in the STL to pick up your file instead of the intended UCRT file (which is where `PTRDIFF_MAX` is defined). This can be seen in the output of `/showIncludes`:

```
Note: including file:            C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.41.34021\include\type_traits
Note: including file:             C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.41.34021\include\cstdint
Note: including file:              C:\Temp\DELME\Motion\src\Lib\EtherCAT\osal\win32\stdint.h
```

To fix this, you need to avoid conflicting with the names of C Standard Library header files. Hope this helps!

**Closed by StephanTLavavej** 2024-07-17 21:20 UTC
Labels: invalid
