### ISSUE TITLE
<array>: array<string_view, 0> cannot be value initialized with braces during constexpr evaluation

### ISSUE THREAD

**Issue by CalebAdrianXYZ** [microsoft/STL#3685] opened 2023-05-08 17:41 UTC
# Describe the bug
Value initializing `array<string_view, 0>` using braces (with no arguments) is rejected during constexpr evaluation, see `rejected()` below. A few work arounds (see `workaround1()` and `workaround2()`) are provided and shown to compile, including an minimal "alternative" array type which compiles with the expected expression (see `works()`). Given the errors MSVC produces, I believe this is an issue with `array` and not `string_view` specifically, despite working with other types such as `int`.

# Command-line test case
```cpp
C:\Temp>type repro.cpp
#include <array>
#include <string_view>
#include <cstddef>

template<typename T>
constexpr auto rejected() {
    return std::array<T, 0>{};
}

template<typename T>
constexpr auto workaround1() {
    return std::array<T, 0>();
}

template<typename T>
constexpr auto workaround2() {
    std::array<T, 0> a{};
    return a;
}

static_assert(rejected<int>().empty());
static_assert(rejected<std::string_view>().empty()); // msvc rejects this
static_assert(workaround1<int>().empty());
static_assert(workaround1<std::string_view>().empty());
static_assert(workaround2<int>().empty());
static_assert(workaround2<std::string_view>().empty());

template<typename T, std::size_t N>
struct my_array {
    T data[N];
    static constexpr bool empty() { return false; }
};

template<typename T>
struct my_array<T, 0> {
    static constexpr bool empty() { return true; }
};

template<typename T>
constexpr auto works() {
    return my_array<T, 0>{};
}

static_assert(works<int>().empty());
static_assert(works<std::string_view>().empty());

C:\Temp>cl /EHsc /W4 /WX /std:c++20 /nologo .\repro.cpp
repro.cpp
<source>(21): error C3615: constexpr function 'rejected' cannot result in a constant expression
<source>(21): note: failure was caused by call of undefined function or one not declared 'constexpr'
<source>(21): note: see usage of '__builtin_array_init_helper'
Compiler returned: 2
```

# Expected behavior
The code should compile without the need for various workarounds. The code is currently accepted by GCC, Clang (libstdc++ and libc++), NVC++, and ICX. (See CE link below)

# STL version
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32530 for x64

# Additional context
CE link: https://godbolt.org/z/3bc5PrTn3

**Comment by frederick-vs-ja** [comment] 2023-05-09 01:57
This is probably a compiler bug. I've filed DevCom-10357920.

Reduced example ([Godbolt link](https://godbolt.org/z/5jGofqG93)):
```c++
struct MyTrivialClass {
    unsigned int size_;
};

struct MyClass {
    unsigned int size_ = 0u;
};

template<class T>
struct MyArr {
    T elem[1];
    constexpr bool test() const noexcept { return true; }
};

template<class T>
constexpr auto ListInit() {
    return MyArr<T>{};
}

template<class T>
constexpr auto NonListInit() {
    return MyArr<T>();
}

static_assert(ListInit<int>().test(), "");
static_assert(ListInit<MyTrivialClass>().test(), "");
static_assert(ListInit<MyClass>().test(), ""); // rejected by MSVC since C++20 mode

static_assert(NonListInit<int>().test(), "");
static_assert(NonListInit<MyTrivialClass>().test(), "");
static_assert(NonListInit<MyClass>().test(), "");
```

**Comment by StephanTLavavej** [comment] 2023-05-10 21:22
Thanks @frederick-vs-ja for filing the DevCom issue! I've sent a mail to the compiler FE team asking them to check whether this is a unique bug. (It appears that it was resolved as a duplicate by DevCom triage and that no compiler FE dev has analyzed the issue yet.)

**Comment by StephanTLavavej** [comment] 2023-05-10 22:12
Our `constexpr` maintainer tracked this down. We believe that it was fixed by internal MSVC-PR-325596 which wasn't present in 17.6, but will be shipping in 17.7p1. It might not have been an exact duplicate but appears to have shared the same root cause. He verified that your repro failed before this PR and compiles after.

We can wait for 17.7p1 to ship and then close this issue after verifying with the public build.

**Comment by frederick-vs-ja** [comment] 2023-05-19 18:15
I've verified that the original example and my reduced one are accepted by MSVC in C++20/23 modes in VS 2022 17.7p1.

**Comment by CaseyCarter** [comment] 2023-05-19 18:42
> I've verified that the original example and my reduced one are accepted by MSVC in C++20/23 modes in VS 2022 17.7p1.

Thanks! We'll call this closed, then.

**Closed by CaseyCarter** 2023-05-19 18:42 UTC
Labels: bug, compiler
