### ISSUE TITLE
`<cmath>`: quiet floating-point comparisons cause ambiguous call to overloaded function

### ISSUE THREAD

**Issue by sergiud** [microsoft/STL#2562] opened 2022-02-11 16:49 UTC
**Describe the bug**
Using declaration of quiet floating-point comparison functions in a namespace that overloads them causes ambiguous call errors.

**Command-line test case**
```cpp
#include <cmath>
#include <type_traits>

using std::isless;
// Same problem is caused by other comparison functions

struct MyType {};

template<class T>
struct IsMyType : std::false_type {};

template<>
struct IsMyType<MyType> : std::true_type {};

template<class Lhs, class Rhs, std::enable_if_t<IsMyType<Lhs>::value || IsMyType<Rhs>::value>* = nullptr>
bool isless(const Lhs& lhs, const Rhs& rhs) { return false; }

int main()
{
	isless(MyType{}, 1.0);
        // same problem: isless(MyType{}, MyType{});
}
```

```console
D:\>cl /std:c++14 fpbug.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30709 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

fpbug.cpp
fpbug.cpp(19): error C2668: 'isless': ambiguous call to overloaded function
fpbug.cpp(15): note: could be 'bool isless<MyType,double,0x0>(const Lhs &,const Rhs &)'
        with
        [
            Lhs=MyType,
            Rhs=double
        ]
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_math.h(435): note: or       'bool isless<MyType,double>(_Ty1,_Ty2) throw()'
        with
        [
            _Ty1=MyType,
            _Ty2=double
        ]
fpbug.cpp(19): note: while trying to match the argument list '(MyType, double)'
```

**Expected behavior**
No ambiguity in overloaded functions.

**STL version**
```
Microsoft Visual Studio Community 2022 (64-bit) 
Version 17.0.6
```

**Comment by sergiud** [comment] 2022-02-11 17:42
`std::is_arithmetic` is too generic for floating-point functions. `std::is_floating_point` would probably suffice.

**Comment by MattStephanson** [comment] 2022-02-11 18:10
> `std::is_arithmetic` is too generic for floating-point functions. `std::is_floating_point` would probably suffice.
> 
> Edit: A promotion between a mix of integral and floating-point types must be considered as well. However, cppreference notes:

Yes, this is [[cmath.syn]/2](https://eel.is/c++draft/numerics#cmath.syn-2). There are several examples of it, such as the templated version of 3-argument `hypot`:
https://github.com/microsoft/STL/blob/bbd5dbaa61f192b393d12ea75a2dae1b8a014e7a/stl/inc/cmath#L1223-L1229

**Comment by sergiud** [comment] 2022-02-11 18:18
This implementation would break if the comparisons are specialized for `!std::is_floating_point` which is not disjoint to `std::is_arithmetic`, no?

**Comment by MattStephanson** [comment] 2022-02-11 18:49
I don't think you can use the template version just for the integral case. As I understand it, even `meow(1.0f, 1.0)` is ambiguous for `meow(float,float)` vs. `meow(double,double)`. There's already precedent in the STL code for how to handle this, so unless someone can come up with an example that doesn't follow what the Standard says, I think it's best to stick to that same style.

**Comment by sergiud** [comment] 2022-02-11 19:12
That's not what I meant. Consider `isless(1, 2)` or any other quiet comparison. By constraining in terms `std::is_arithmetic`, the STL overload will still apply although (1) this does not make any sense (2) prevents specializations. Correct?

**Comment by MattStephanson** [comment] 2022-02-11 19:28
Okay, I had a feeling I wasn't quite understanding. In the case of `isless(1,2)`, then yes, the STL version will apply (assuming, as in your original example, you've done `using std::isless`). But (1) even if you think it doesn't make sense, that's what the Standard requires, and (2) what you can't specialize is `::std::isless`. You could, for example, put `MyType` and an overload for `isless` in your own namespace and rely on ADL to find your overload. For example, https://godbolt.org/z/8abfcKaE4. There's also the "hidden friend" idiom, as discussed in https://quuxplusone.github.io/blog/2020/07/11/the-std-swap-two-step/, which is now commonly used in the STL for `operator==`.

**Comment by sergiud** [comment] 2022-02-11 19:45
> You could, for example, put MyType and an overload for isless in your own namespace and rely on ADL to find your overload.

This is actually my current use case which does not work with MSVC. Simply switching the compiler shows the original problem: https://godbolt.org/z/8orTh4Yx6.

**Comment by MattStephanson** [comment] 2022-02-11 19:54
> This is actually my current use case which does not work with MSVC. Simply switching the compiler shows the original problem: https://godbolt.org/z/8orTh4Yx6.

Yes, my point is just that fixing it by constraining the `std` version on `is_arithmetic` does not prevent you from specializing (well, you're not allowed to *specialize* `::std::isless`, but it will let you have your own *overload*). Constraining on `!is_floating_point` would be too weak, because it would be satisfied by any user-defined type, so you would still end up with ambiguous overloads.

**Comment by sergiud** [comment] 2022-02-11 19:58
Thanks for the clarification!

**Comment by frederick-vs-ja** [comment] 2022-02-12 09:20
I guess this might be a bug in the C++ standard. The standard currently doesn't specify whether and how the additional overloads are constrained.

**Comment by MattStephanson** [comment] 2022-02-12 16:56
> I guess this might be a bug in the C++ standard. The standard currently doesn't specify whether and how the additional overloads are constrained.

[[cmath.syn]/2](https://eel.is/c++draft/numerics#cmath.syn-2) refers to "argument[s] of arithmetic type", and [[basic.fundamental]/13](https://eel.is/c++draft/basic.fundamental#13) defines those to be all integral and floating-point types.

The wording says "additional overloads" rather than "constrained". But there are (I think) 19 distinct arithmetic types, so there would be more than 350 overloads if you wrote each permutation explicitly. A constrained template isn't required, but is an efficient way to generate all needed overloads.

**Comment by MattStephanson** [comment] 2022-02-15 00:51
The discussion around #2530 suggests that this actually can't be fixed with a wrapper in `<cmath>`. @CaseyCarter points out on the Discord that `using namespace std; isless(1.0, 1.0);` would become ambiguous for `::isless` vs. `std::isless`. I don't know why I didn't realize sooner, but for user-defined types it also wouldn't eliminate the ambiguity between the user's overload and the one in the global namespace. So, I think any fix for this would have to involve the UCRT. cc @stwish-msft.

**Comment by stwish-msft** [comment] 2022-02-16 23:07
I've opened this as a UCRT issue: "Unconstrained templates in math.h, ex: 'isless'"

**Comment by CaseyCarter** [comment] 2022-02-16 23:23
Thanks, Steve! Closing this as external, since the problem is in the UCRT / Windows SDK.

**Closed by CaseyCarter** 2022-02-16 23:23 UTC
Labels: bug, external
