### ISSUE TITLE
EDG (still) ICEs when consuming Standard Library Header Units

### ISSUE THREAD

**Issue by CaseyCarter** [microsoft/STL#4957] opened 2024-09-14 02:41 UTC
`P1502R1_standard_library_header_units` is disabled for EDG with annotation `TRANSITION, VSO-1232145 "EDG ICEs when consuming Standard Library Header Units"`:

https://github.com/microsoft/STL/blob/73b5791e5c9eff1ece3ce593571fb30c31bf08d9/tests/std/tests/P1502R1_standard_library_header_units/env.lst#L22

VSO-1232145 was closed 2024-07-05. It's listed as "fixed" in #1694 but the test is nonetheless disabled. Enabling the test shows that it still ICEs.

#1621 _does_ state that "EDG is currently investigating test failures. STL test coverage is not yet enabled." which could be intended as a blanket statement that we know there are problems and we are not tracking them individually.

We need to either reduce and report a new EDG issue or, if my "blanket statement" interpretation is correct, update the `TRANSITION` comment to point at GH-1621.

**Comment by StephanTLavavej** [comment] 2024-09-18 21:49
We talked about this at the weekly maintainer meeting. We know there are issues with EDG processing header units and named modules. Our understanding is that EDG is working on getting the header units test to compile, but (as with concepts earlier) analyzing/reducing/reporting individual issues would really help them.

We'll update the test workaround comment, but the real work that needs to happen here is investigating what blocking issues remain. We're going to resolve this as a duplicate of #1621 and fuse this into that issue.

**Closed by StephanTLavavej** 2024-09-18 21:49 UTC
Labels: test, modules
