### ISSUE TITLE
Can I revamp the std::deque in MSVC STL?

### ISSUE THREAD

**Issue by expnkx** [microsoft/STL#1254] opened 2020-09-01 19:18 UTC
std::deque in MSVC STL is extremely slow (at least 10x slower) and not written in the way it is designed or what standard requires it to be.

std::deque is designed the way nearly the same performance as std::vector. extremely fast for insertion compared to vector. A little bit slower of iterator accessing due to redundant bounds check. (That proves bounds checking is terrible).

I hate std::vector. It is not as efficient as deque.

That pisses me off for over 5 years since std::stack and std::queue they all rely on std::deque and std::deque is technically the fastest container for these data structures.

I am not going to touch it before C++20. Rewrite it in C++20 with Concepts to avoid problems.

**Comment by MikeGitb** [comment] 2020-09-01 20:48
My guess is (not a maintainer) that you have to wait for the next abi-incompatible version of VS and that whatever you write will still have to work in c++14 mode or whatever the oldest supported standard version will be (you can of course #ifdef the different versions,  but a deque compiled with c++14 should probably still be ABI compatible with a c++20 version).

But again: That is just my assumption.

**Comment by expnkx** [comment] 2020-09-01 20:52
> My guess is (not a maintainer) that you have to wait for the next abi-incompatible version of VS and that whatever you write will still have to work in c++14 mode or whatever the oldest supported standard version will be (you can of course #ifdef the different versions, but a deque compiled with c++14 should probably still be ABI compatible with a c++20 version).
> 
> But again: That is just my assumption.

The ugliness of standard containers before C++20 is completely unbearable. SFINAE just ends up with unmaintainable crap.

I think just do not touch code before C++20 would be a better option and won't break ABIs if people choose to continue using C++17 or C++14.

**Comment by sylveon** [comment] 2020-09-01 22:13
I believe there are already improvements to deque in the (currently private) vNext branch.

**Comment by StephanTLavavej** [comment] 2020-09-02 06:31
Closing this as a duplicate of #147. As @MikeGitb mentioned, changing `deque`'s representation will break binary compatibility, so this has to wait for vNext. At this time, it's uncertain as to whether vNext will support C++14 and C++17 modes; I suspect that it will. Whatever Standard modes it supports, they will all have to be binary-compatible with each other - we *never* allow Standard mode to affect bincompat.

@sylveon - we accumulated a bunch of improvements in our (stranded in Team Foundation Version Control) vNext branch, but `deque` wasn't among them - its representation was not yet changed. In fact, I overhauled all of the container iterators *except* `deque` and `vector<bool>` due to time limitations (they will eventually be overhauled for sure).

@expnkx - Please don't use the "cxx20 Feature" issue template, which is clearly marked "For STL maintainers only". Please use the Bug Report or Question issue templates.

**Closed by StephanTLavavej** 2020-09-02 06:31 UTC
Labels: question

**Comment by expnkx** [comment] 2020-09-02 06:35
> Closing this as a duplicate of #147. As @MikeGitb mentioned, changing `deque`'s representation will break binary compatibility, so this has to wait for vNext. At this time, it's uncertain as to whether vNext will support C++14 and C++17 modes; I suspect that it will. Whatever Standard modes it supports, they will all have to be binary-compatible with each other - we _never_ allow Standard mode to affect bincompat.
> 
> @sylveon - we accumulated a bunch of improvements in our (stranded in Team Foundation Version Control) vNext branch, but `deque` wasn't among them - its representation was not yet changed. In fact, I overhauled all of the container iterators _except_ `deque` and `vector<bool>` due to time limitations (they will eventually be overhauled for sure).
> 
> @expnkx - Please don't use the "cxx20 Feature" issue template, which is clearly marked "For STL maintainers only". Please use the Bug Report or Question issue templates.

Unfortunately. MSVC stl has a very long history of implementing things poorly in the first place. Including std::streambuf. I hope you guys will not make same mistake in the future.
