### ISSUE TITLE
<cmath>: std::isnan missing IntegralType overload

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/STL#3400] opened 2023-02-10 15:16 UTC
**Describe the bug**
[`std::isnan`](https://en.cppreference.com/w/cpp/numeric/math/isnan) is supposed to have an overload for all integral types. The lack of this overload triggers C2668 when called using an `unsigned short`. 

**[Godbolt](https://godbolt.org/z/n9Y9najcd)**

**Expected behavior**
Call proper overload (casting to `double`).

**STL version**
```
Microsoft Visual Studio Build Tools 2022
Version 17.4.4
```

**Comment by frederick-vs-ja** [comment] 2023-02-10 16:10
Duplicate of #519

This is LWG-1327 which is #resolved in C++11. Unfortunately, the overloads are currently provided in UCRT, and a complete resolution cannot be achieved in this repo.

**Closed** 2023-02-10 23:05 UTC
Labels: bug, duplicate
