### ISSUE TITLE
<variant>: Inherited constructors issue

### ISSUE THREAD

**Issue by sdebionne** [microsoft/STL#1737] opened 2021-03-15 08:31 UTC
**Describe the bug**
The following code fails to compile, while it works on clang > 4 and gcc > 7. The `foos`'s converting constructor should not be instantiated. The issue is similar to the one reported in Boost.Variant2 (refer to boostorg/variant2#26) and fixed in develop (boostorg/variant2@3bc9a57c9b159fcae2f512f5ef29513ff94d4582).

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <variant>

template <typename ...T>
class any_type : std::variant<T...>
{
    using parent_t = std::variant<T...>;

    using parent_t::parent_t;
};

struct foo
{
    foo() {}
    foo(int i_arg) : i(i_arg) {}
    foo(foo const& rhs) {}

    template <typename T>
    foo(T const& rhs) {
        rhs.bar();
    }

    int i{ 0 };
};

int main(int argc, char* argv[])
{
    using any_t = any_type<int, double, foo>;

    any_t a(1);
    any_t b(a);
}

C:\Temp>cl /std:c++17 .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29910 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
.\repro.cpp(19): error C2039: 'bar': is not a member of 'any_type<int,double,foo>'
.\repro.cpp(27): note: see declaration of 'any_type<int,double,foo>'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\variant(465): note: see reference to function template instantiation 'foo::foo<any_t>(const T &)' being compiled
        with
        [
            T=any_t
        ]
...
```

**Expected behavior**
` repro.cpp` should compile.

**STL version**
Visual Studio 2019 Community
Version 16.9.0

**Comment by CaseyCarter** [comment] 2021-03-15 21:47
This reproduces with MSVC, but not when compiling with clang - which suggests an MSVC bug with inheriting constructors. We'll need to reduce to something library-free (which may not be simple given the complicated metaprogramming that supports `variant`'s constructor overloads) and report.

**Comment by cpplearner** [comment] 2021-03-17 15:23
It seems that MSVC calls the base class constructor template for `any_type b(a)`, while other compilers do not.

```c++
template<class T, class U>
constexpr bool is_same_v = false;
template<class T>
constexpr bool is_same_v<T,T> = true;

struct any_t;
template<class... Args>
struct variant {
    template<class T>
    variant(T&&) {
        static_assert(!is_same_v<T, any_t&>);
    }
};

struct any_t : variant<int> {
    using variant::variant;
};

int main() {
    any_t a(1);
    any_t b(a);
}
```

**Comment by sdebionne** [comment] 2021-03-18 09:24
Thank you @cpplearner, your library-free code seems to capture the issue well -checked on Compiler Explorer. Are you willing to [report it to the MSVC++ team](https://docs.microsoft.com/en-us/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=msvc-160)?

**Comment by CaseyCarter** [comment] 2021-03-18 10:43
Reduced a bit more (https://godbolt.org/z/cMfh9E):
```c++
template<class, class>
constexpr bool is_same_v = false;
template<class T>
constexpr bool is_same_v<T,T> = true;

struct variant {
    template<class U>
    variant(U&&) {
        static_assert(is_same_v<U, int>);
    }
};

struct any_t : variant {
    using variant::variant;
};

int main() {
    any_t a(1);
    any_t b(a);
}
```
Looks like MSVC doesn't implement [[over.match.funcs.general]/9](http://eel.is/c++draft/over.match.funcs.general#9):

> A constructor inherited from class type `C` ([class.inhctor.init]) that has a first parameter of type “reference to _cv1_ `P`” (including such a constructor instantiated from a template) is excluded from the set of candidate functions when constructing an object of type _cv2_ `D` if the argument list has exactly one argument and `C` is reference-related to `P` and `P` is reference-related to `D`.

which comes from [CWG-2356](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2356) that was accepted as a defect report against C++17.

I've reported this as DevCom-1374682, feel free to follow there for status. Since this is a compiler bug and not an STL bug, I'm closing this issue and resolving as "external".

**Closed by CaseyCarter** 2021-03-18 10:43 UTC
Labels: external
