### ISSUE TITLE
Consider adding test coverage for /Zc:alignedNew-

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1691] opened 2021-02-24 01:22 UTC
Currently, we have no test coverage for [`/Zc:alignedNew-`](https://docs.microsoft.com/en-us/cpp/build/reference/zc-alignednew?view=msvc-160) aside from the feature-test macros test:

https://github.com/microsoft/STL/blob/3c13e3ec1db421c1992ac2782c301d7a2da7aa35/tests/std/tests/VSO_0157762_feature_test_macros/env.lst#L36

As C++17/20 without over-aligned allocation is an unusual mode, we can break it - see #1689. We should consider adding test coverage, but we need to think about the best way to do so - adding distinct configurations is expensive.

**Comment by CaseyCarter** [comment] 2022-06-24 13:39
Closing as duplicate of the newer and more detailed #2713.

**Closed by CaseyCarter** 2022-06-24 13:39 UTC
Labels: duplicate, test
