### ISSUE TITLE
Standard references should be updated to N4849

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#476] opened 2020-01-31 01:11 UTC
In the January of 2020 mailing, a new version of the C++ standard, N4849 is available (https://wg21.link/std as of this writing). We should find all the `N\d\d\d\d` standard references and update their N number and paragraph reference to the latest working paper.

**Comment by BillyONeal** [comment] 2020-01-31 01:13
(To do this, grep the source tree for `N\d\d\d\d`, find the `[stable.name]` in the new standard, find the appropriate corresponding paragraph number, and update any quoted standards text as appropriate)

**Comment by StephanTLavavej** [comment] 2020-01-31 01:14
This is a duplicate of #182.

**Comment by BillyONeal** [comment] 2020-01-31 01:16
It seems like the way #182 is formulated it can never be completed though. It seems like we should have a specifically actionable "update to N1234" issue created whenever a new WP comes out.

**Closed** 2020-01-31 01:15 UTC
Labels: documentation, duplicate, enhancement

**Comment by StephanTLavavej** [comment] 2020-01-31 01:19
In the discussion for #182, we had tentatively decided on an initial cleanup to the current WP, followed by successive issues for each published standard - because yes, it is an evergreen task, but updating to literally every new WP is not necessary.
