### ISSUE TITLE
<chrono>: Parsing "00:00:60" as `utc_time` incorrectly returns 00:00:59.0000000

### ISSUE THREAD

**Issue by statementreply** [microsoft/STL#2698] opened 2022-05-03 13:09 UTC
**Command-line test case**
```
C:\Users\He\source\test>type chronat.cpp
```
```cpp
#include <chrono>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>

using namespace std;
using namespace std::chrono;

int main() {
    try {
        utc_clock::time_point t;
        if (istringstream{"2021-08-28 00:00:60"} >> parse("%F %T"s, t)) {
            cout << t << "\n";
        } else {
            cout << "parse failed\n";
        }
    } catch (const exception& e) {
        cout << "error: " << e.what() << "\n";
    }
    return 0;
}
```
```
C:\Users\He\source\test>cl /EHsc /W4 /WX /std:c++20 chronat.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.32.31328 版
版权所有(C) Microsoft Corporation。保留所有权利。

chronat.cpp
Microsoft (R) Incremental Linker Version 14.32.31328.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:chronat.exe
chronat.obj

C:\Users\He\source\test>.\chronat.exe
2021-08-28 00:00:59.0000000
```

**Expected behavior**
Prints either "parse failed" or "2021-08-28 00:00:59.9999999", depending on the design choice.

**STL version**
Microsoft Visual Studio Community 2022 (64 位) - Preview
版本 17.2.0 Preview 5.0

**Comment by PallHaraldsson** [comment] 2022-05-03 15:02
FYI "60" is correct (for leap second) according to https://en.wikipedia.org/wiki/ISO_8601#Times

So I guess you can close this issue.

Not all support it, seeing this issue made me think so I asked, and pointed out, here:
https://discourse.julialang.org/t/parsing-datetime-what-should-be-the-default-s/80428

There's an answer, with a question regarding it there.

**Comment by PallHaraldsson** [comment] 2022-05-03 16:27
Sorry it seems actually parsing e,g, "xx:00:60" is always wrong. 

I see in Java code:
https://gist.github.com/dehora/9b2ce8bac22d1b37393d8b4f7c9eb7aa
```
if (raw.contains(":59:60")) {
```

Found at https://stackoverflow.com/questions/48009870/parsing-localtime-with-leap-second


I'm not sure what's demanded by the standards, up you should round down, or maybe up (then would hit next day even year).

**Comment by MattStephanson** [comment] 2022-05-04 01:00
My opinion is that there is no corresponding `utc_time`, so this parse should fail per [[time.parse]/16](https://eel.is/c++draft/time.parse#16). The issue is that the logic to check for a valid leap second is only taken if the hour and minute equal 23 and 59:
https://github.com/microsoft/STL/blob/39332e104d5274b8b1f48ebe380ba1dfc7ce4cc0/stl/inc/chrono#L3492-L3495

Off the top of my head, I think it would be easiest to fix slightly earlier, here:
https://github.com/microsoft/STL/blob/39332e104d5274b8b1f48ebe380ba1dfc7ce4cc0/stl/inc/chrono#L3388-L3390
where the upper bound for `_Second` can be changed to `(_Hour_24 == 23 && _Minute == 59) ? 60 : 59`.

**Closed** 2022-06-20 00:07 UTC
Labels: bug, chrono
