### ISSUE TITLE
<syncstream>: std::osyncstream memory leak

### ISSUE THREAD

**Issue by segeter** [microsoft/STL#2819] opened 2022-06-23 03:36 UTC
Problem Description:
Memory leak occurs when I use std::setw(32)。
Not sure if it's the same issue as #2763 and #2760

My test code：
![image](https://user-images.githubusercontent.com/52019351/175203146-eefd8ba4-bf5b-49cf-becf-9631c0a5d514.png)

Before the cycle starts：
![image](https://user-images.githubusercontent.com/52019351/175203313-8a54ba03-ec60-490f-b882-a90c696fe871.png)

Cycle after a while:
![2](https://user-images.githubusercontent.com/52019351/175203404-cf1fea87-548d-41e9-b2c0-96bd7e8c581f.png)

**Comment by segeter** [comment] 2022-06-23 03:43
Track analysis, tips here：
![1](https://user-images.githubusercontent.com/52019351/175204357-c717acfc-53a6-4f62-9428-b34cbc18b672.png)

**Comment by CaseyCarter** [comment] 2022-06-23 04:49
@fsb4000 do you want to take a look at this and determine if it's a duplicate? Feel free to say no and I'll investigate - I just thought I'd give you first right of refusal since you last touched this.

**Comment by fsb4000** [comment] 2022-06-23 04:51
Sure, I will build against `main` and test it.

**Comment by fsb4000** [comment] 2022-06-23 05:06
Yeah, it is not reproducible on `main`
![изображение](https://user-images.githubusercontent.com/4289847/175217007-93d377a9-0e8d-4c4e-aa80-e6e385afad9b.png)
![изображение](https://user-images.githubusercontent.com/4289847/175217350-7f80871f-3ca5-4402-8176-4fb438ff20ff.png)

(I'm showing "committed memory" instead of "working set" in task manager)

**Comment by fsb4000** [comment] 2022-06-23 05:11
and yes, on Visual Studio 2022 Professional 17.2.4, I also have the memory leak.

**Comment by CaseyCarter** [comment] 2022-06-23 05:17
Thanks, @fsb4000! Looks like this is definitely a duplicate of #2760.

**Closed by CaseyCarter** 2022-06-23 05:17 UTC
Labels: bug, duplicate
