### ISSUE TITLE
`<type_traits>`: `common_reference` workaround still necessary?

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2650] opened 2022-04-13 06:16 UTC
VS 2022 17.2 Preview 3 is now available. It contains internal MSVC-PR-382810 that fixed DevCom-876860 and its internal mirror VSO-1049320. We have workarounds for both bug numbers:

https://github.com/microsoft/STL/blob/52505b9d3249c50b33eb22152a1f18f208ea2959/stl/inc/type_traits#L1248-L1274
https://github.com/microsoft/STL/blob/52505b9d3249c50b33eb22152a1f18f208ea2959/tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp#L217-L221

The `P0784R7_library_support_for_more_constexpr_containers/test.cpp` workaround can apparently be removed without issue. However, attempting to remove the `<type_traits>` workaround (which was added by GH-2592) causes a libcxx test to fail, `llvm-project\libcxx\test\std\concepts\concepts.lang\concept.commonref\common_reference.compile.pass.cpp`.

```
common_reference.compile.pass.cpp(38): error C2338: static_assert failed: 'std::common_reference_with<volatile T&, volatile U&&>'
common_reference.compile.pass.cpp(61): note: see reference to function template instantiation 'bool CheckCommonReferenceWith<int[5],int[5]>(void) noexcept' being compiled
common_reference.compile.pass.cpp(44): error C2607: static assertion failed
```

I don't know if this is:

* Remaining compiler bugginess that needs to be reported
* A library bug somewhere
* A libcxx test bug

**Comment by StephanTLavavej** [comment] 2022-04-13 06:43
I suspect this may be remaining compiler bugginess - I experienced a bunch of compiler and test crashes with this workaround removal plus other changes, and I seem to be able to restore all my *other* changes without incident (I haven't tried running a full test pass with just the workaround removal yet).

**Comment by CaseyCarter** [comment] 2022-10-24 19:28
This is a duplicate of #2860.

**Closed by CaseyCarter** 2022-10-24 19:28 UTC
Labels: test
