### ISSUE TITLE
<mutex>: Implement mutex and recursive_mutex on SRW Lock. Support recursion only on recursive_mutex

### ISSUE THREAD

**Issue by AlexGuteniev** [microsoft/STL#654] opened 2020-03-29 07:17 UTC
- correctness (constexpr construction)
- no undesired strengthening (recursion on non-recursive deliberately not behaving correctly)
- performance (no dynamic API binding => no control flow guard overhead; no recursion support overhead)

I expect it is already done in ABI-breaking branch.

**vNext note:** Resolving this issue will require breaking binary compatibility. We won't be able to accept pull requests for this issue until the vNext branch is available. See #169 for more information.

**Comment by StephanTLavavej** [comment] 2020-07-09 10:01
Closing as duplicate of #946 (using that one as the primary, even though it was filed later, because it's linked to DevCom/VSO bugs).

**Closed by StephanTLavavej** 2020-07-09 10:01 UTC
Labels: bug, duplicate, vNext
