### ISSUE TITLE
Which Visual Studio 2022 BuildTools MSVC is the best version for Cuda 11.8 and Cuda 12.4 and so

### ISSUE THREAD

**Issue by FurkanGozukara** [microsoft/STL#4941] opened 2024-09-06 16:22 UTC
I keep having issues when compiling apps that requires CUDA and C++ tools on windows

I would like to learn best version for CUDA 11.8 and CUDA 12.4

There are so many versions listed here and not all of them working

https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history

For example recently I am compiling XPose and it is so sensitive to the C++ versions

Which version from above list do you suggest?

The list starts from 17.0 to 17.10

Can we say that LTSC 17.10 is better than LTSC 17.4

I really need help with this

**Comment by frederick-vs-ja** [comment] 2024-09-06 17:08
Ideally the latest version should be the best, although there can possibly be unexpected regressions. Feel free to report bugs.

**Comment by FurkanGozukara** [comment] 2024-09-06 17:11
> Ideally the latest version should be the best, although there can possibly be unexpected regressions. Feel free to report bugs.

Latest version doesn't work with CUDA 11.8

**Comment by frederick-vs-ja** [comment] 2024-09-06 17:16
> > Ideally the latest version should be the best, although there can possibly be unexpected regressions. Feel free to report bugs.
> 
> Latest version doesn't work with CUDA 11.8

Oh, I forgot to say that the version of CUDA should also be the latest.

The support for CUDA before 12.4 was dropped by #4475 which was merged in VS 2022 17.11. So 17.10 should be OK for CUDA 11.8.

**Comment by FurkanGozukara** [comment] 2024-09-06 17:42
> > > Ideally the latest version should be the best, although there can possibly be unexpected regressions. Feel free to report bugs.
> > 
> > 
> > Latest version doesn't work with CUDA 11.8
> 
> Oh, I forgot to say that the version of CUDA should also be the latest.
> 
> The support for CUDA before 12.4 was dropped by #4475 which was merged in VS 2022 17.11. So 17.10 should be OK for CUDA 11.8.

thanks . are there any place that shows 17.10 supports which cuda list? or like 17.8? also an app that works with cuda 11.8, would work 100% with cuda 12.4 if compiled with 17.11 can we tell that?

**Comment by StephanTLavavej** [comment] 2024-09-06 23:28
Here's the full history. It helps to know that CUDA rejects *too-new* VS versions (for having a too-large `_MSC_VER` value; they care about the first 3 digits), while MSVC's STL requires a minimum CUDA version and rejects *too-old* CUDA versions. (This is because we depend on new features and bugfixes.) MSVC's STL never rejects newer CUDA versions, although we only test with the specific version we require.

CUDA has an escape hatch compiler option, and MSVC's STL has an escape hatch macro, that disable this enforcement. Escape-hatching CUDA to allow a newer VS version is very likely to work. Escape-hatching MSVC's STL to use an older CUDA version is much more perilous.

* CUDA 10.1 RTW began allowing VS 2019 16.0 (`_MSC_VER=1920`).
* VS 2019 16.10 began requiring CUDA 10.1 Update 2. (#1544)
* CUDA 11.6.0 began allowing VS 2022 17.0 (`_MSC_VER=1930`).
* VS 2022 17.4 began requiring CUDA 11.6.0. (#2791)
* CUDA 12.4.0 began allowing VS 2022 17.10 (`_MSC_VER=1940`).
* VS 2022 17.11 began requiring CUDA 12.4.0. (#4475)

We recommend that you use the latest VS version (an even-numbered Long-Term Support release, if that's what you prefer) and the latest CUDA version.

**Closed by StephanTLavavej** 2024-09-06 23:28 UTC
Labels: question
