### ISSUE TITLE
14.36.32323\include\type_traits(2117,13): error C2678 `_Bitmask=std::filesystem::directory_options`

### ISSUE THREAD

**Issue by shithappens2016** [microsoft/STL#3545] opened 2023-03-07 00:11 UTC
17.6.0 Preview 1.0

```C++
 for (auto const &dir_entry : std::filesystem::recursive_directory_iterator{path}) {}
```

```
/std:c++latest
/experimental:module
```

```bash
[build] C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.36.32323\include\type_traits(2117,13): error C2678
[build]           with
[build]           [
[build]               _Bitmask=std::filesystem::directory_options
[build]           ]
[build] C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.36.32323\include\cstddef(49,39): message : “std::byte std::operator &(const std::byte,const std::byte) noexcept”
```

**Comment by StephanTLavavej** [comment] 2023-03-07 00:48
Thanks for reporting this issue. It's a duplicate of #3330, and we've fixed it in the upcoming VS 2022 17.6 Preview 2 release. (We merged a library workaround #3331, and then the underlying compiler bug plus another affecting directory iterators was fixed in the same 17.6 Preview 2 release.)

As an aside, your build system is somehow omitting crucial parts of the compiler error output, e.g. everything after "error C2678". I was able to recognize the bug anyways, but for other bug reports, it would be invaluable to have the full compiler output. Additionally, you should report bugs with complete self-contained test cases, not snippets - C++ is a complicated language and any individual line might be critical to reproducing a bug, which is easily missed if maintainers have to "fill in the blanks" for a snippet.

**Closed by StephanTLavavej** 2023-03-07 00:48 UTC
Labels: duplicate, modules

**Comment by shithappens2016** [comment] 2023-03-15 02:28
@StephanTLavavej 
I upgraded to 17.6 Preview 2 today. The problem ivs still there.

**Comment by StephanTLavavej** [comment] 2023-03-15 05:20
@shithappens2016 Can you please provide a self-contained test case? I observe that this bug is fixed:

```
C:\Temp>"C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.6.0-pre.2.0
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Temp>type meow.cpp
import std;
int main() {
    const std::filesystem::path p{R"(C:\Temp)"};
    for (auto const& dir_entry : std::filesystem::recursive_directory_iterator{p}) {
        (void) dir_entry;
    }
}

C:\Temp>cl /EHsc /nologo /W4 /MTd /Od /std:c++latest "%VCToolsInstallDir%\modules\std.ixx" meow.cpp /Femeow.exe
std.ixx
meow.cpp
Generating Code...

C:\Temp>
```

Compiler bugs can be *extremely* sensitive to the exact code and compiler options, which is why we need complete test cases and command lines. Thanks!
