### ISSUE TITLE
Shouldn't `std::exception::what()` be declared as `noexcept`?

### ISSUE THREAD

**Issue by EmrecanKaracayir** [microsoft/STL#4852] opened 2024-07-21 17:07 UTC
According to [cppreference](https://en.cppreference.com/w/cpp/error/exception/what), `std::exception::what()` method should be declared as noexcept.

**vcruntime_exception.h**
```cpp

namespace std {

_VCRT_EXPORT_STD class exception
{
public:

    exception() noexcept
        : _Data()
    {
    }

    explicit exception(char const* const _Message) noexcept
        : _Data()
    {
        __std_exception_data _InitData = { _Message, true };
        __std_exception_copy(&_InitData, &_Data);
    }

    exception(char const* const _Message, int) noexcept
        : _Data()
    {
        _Data._What = _Message;
    }

    exception(exception const& _Other) noexcept
        : _Data()
    {
        __std_exception_copy(&_Other._Data, &_Data);
    }

    exception& operator=(exception const& _Other) noexcept
    {
        if (this == &_Other)
        {
            return *this;
        }

        __std_exception_destroy(&_Data);
        __std_exception_copy(&_Other._Data, &_Data);
        return *this;
    }

    virtual ~exception() noexcept
    {
        __std_exception_destroy(&_Data);
    }

    _NODISCARD virtual char const* what() const // Should be noexcept
    {
        return _Data._What ? _Data._What : "Unknown exception";
    }

private:

    __std_exception_data _Data;
};
```

But in MSVC implementation it is not. This is an awful situation because functions marked with noexcept shouldn't call `std::exception::what()`.

**For example:**
```cpp
auto main() noexcept -> int
try
{
  std::cout << "Hello World!\n";
  return EXIT_SUCCESS;
}
catch (const std::exception& exception)
{
  std::cerr << exception.what());
  return EXIT_FAILURE;
}
```

**Resulting with warning:**
```
C26447	The function is declared 'noexcept' but calls function 'what()' which may throw exceptions (f.6).
```

Which is really bad because we are in a catch block, throwing here would terminate the program.

Why MSVC doesn't conform even though `/permissive-` flag is passed?

**Comment by frederick-vs-ja** [comment] 2024-07-22 00:02
Duplicate of #948.
(Although, to be clear, `noexcept` is not a part of function signature.)

**Comment by StephanTLavavej** [comment] 2024-07-24 21:16
Yep, duplicate. I'll consider fixing this in the next major version 18.0 (with an escape hatch, of course) since that seems like a reasonable time, and it's become clear that we can't lump massive source-breaking changes into whenever the binary-breaking vNext release happens (if it hopefully happens).

**Closed by StephanTLavavej** 2024-07-24 21:16 UTC
Labels: bug, duplicate
