### ISSUE TITLE
compile time checking for format strings is not enables by default in 17.7 preview

### ISSUE THREAD

**Issue by AbrasiveBoar902** [microsoft/STL#3710] opened 2023-05-17 15:30 UTC
Instructions
===========
In visual studio 17.6，when I write a wrong format string, there will be an compile time error. However, the same code will pass checking in 17.7 preview.

On-Topic Examples
------------------
`std::format("{} {}", 10)` will not produce an compile error, except `/utf-8` or other some additional options are explicitly set.
Has the behavior of `is execution charset self synchronizing` changed, so I need to config something to change `MSVC EXECUTION CHARACTER SET` to enable the checking?

Off-Topic Examples
------------------

**Comment by StephanTLavavej** [comment] 2023-05-17 21:26
Thanks for the report - this certainly sounds like a bug, we'll investigate.

**Comment by CaseyCarter** [comment] 2023-05-17 22:20
I'm unable to reproduce this locally; I get a compile error both with and without `/utf-8`. What does this:
```c++
#include <print>

int main() {
    std::println("{}", _MSVC_EXECUTION_CHARACTER_SET);
}
```
Output for you when compiled with `cl /std:c++latest /EHsc`?

**Comment by AbrasiveBoar902** [comment] 2023-05-18 12:11
> I'm unable to reproduce this locally; I get a compile error both with and without . What does this:`/utf-8`
> 
> ```c++
> #include <print>
> 
> int main() {
>     std::println("{}", _MSVC_EXECUTION_CHARACTER_SET);
> }
> ```
> 
> Output for you when compiled with ?`cl /std:c++latest /EHsc`

Of course, it is not a self-synchronizing code page.

I rolled back to 17.6 pre 6, but cannot reproduce the behavior before (even intellisense can give a warning about the illegal format strings before.) :-(

However, I have set all the sources and configs to use utf-8, so I think it could check the utf-8 encoded format strings at compile time. Or is there any better ways to enable compile time checking instead of explicitly add additional options?

**Comment by barcharcraz** [comment] 2023-05-18 18:43
it's possible that your old files had UTF-8 or UTF-16 BOMs, which would have caused MSVC to default to a unicode source and execution encoding, barring that it's possible you had a different user codepage selected last time you tried this.

**Comment by AbrasiveBoar902** [comment] 2023-05-18 23:27
> it's possible that your old files had UTF-8 or UTF-16 BOMs, which would have caused MSVC to default to a unicode source and execution encoding, barring that it's possible you had a different user codepage selected last time you tried this.

My old files had a none-self-synchronizing code encoding, and I have changed it to UTF-8 BOMs when using 17.7preview since I found there's no compile time checking. Maybe some other changes have also been made, but I don't have a commit to restore. Since I can't reproduce the behavior before, I will close the issue.

**Comment by CaseyCarter** [comment] 2023-05-19 18:40
I'll close this as "invalid", then. Do let us know if you have any more problems or questions.

**Closed by CaseyCarter** 2023-05-19 18:40 UTC
Labels: bug, format
