### ISSUE TITLE
<cmath>: floating-point classification functions are ambiguous for integer types

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#908] opened 2020-06-18 09:05 UTC
Currently calling a floating-point classification/comparison function in `<cmath>` with an integer value as argument such as `std::isnan(42)` is ambiguous. And the standard says that sufficient overloads are provided for integer types ([[cmath.syn]/2](http://eel.is/c++draft/c.math#cmath.syn-2),  at least since [N3337](https://timsong-cpp.github.io/cppwp/n3337/c.math#11)), so the ambiguity should be resolved.

Overloads of other `<cmath>` functions for integer types are handled in `<cmath>`. So overloads of these functions should also be handled in this header.

**Comment by StephanTLavavej** [comment] 2020-06-21 02:05
Duplicate of #519.

**Closed by StephanTLavavej** 2020-06-21 02:05 UTC
Labels: bug, duplicate
