### ISSUE TITLE
The contents of <string_view> are available only with C++17 or later

### ISSUE THREAD

**Issue by viccpp** [microsoft/STL#2503] opened 2022-01-25 10:39 UTC
**Describe the bug**
Compiler shows meaningless warning about C++17 when only C++14 is used. Builds become very noisy when such `header.h` is included in many project files.

**Command-line test case**

`header.h`:
```
#ifndef HEADER_H
#define HEADER_H

#ifndef __has_include
#   define __has_include(f) 0
#endif

#include<cstddef>
#if __has_include(<string_view>)
#include<string_view>
#endif

void consume(const char *s, std::size_t n);
#if __cpp_lib_string_view // C++17
inline void consume(std::string_view s) { consume(s.data(), s.length()); }
#endif

#endif
```

`main.cpp`:
```
#include"header.h"

int main()
{
    consume("str", 3);
}
```

```
C:\Temp>cl /std:c++14 /c main.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30706 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
The contents of <string_view> are available only with C++17 or later.
```

**Expected behavior**
No any warnings are shown.

**STL version**
See the compiler output above.

**Additional context**

**Comment by AlexGuteniev** [comment] 2022-01-25 11:01
Instead of 
```C++
#if __has_include(<string_view>)
#include<string_view>
#endif
```

You should prefer
```C++
#if defined(__cpp_lib_string_view) || __cplusplus >= 201703L || defined(_MSVC_LANG) && _MSVC_LANG >= 201703L
#include<string_view>
#endif
```

Personally I fined the warning useful.

An escape hatch could be added, that could work like:
```C++
#if __has_include(<string_view>)
#define _SILENCE_HEADERS_CXX17_WARNINGS
#include<string_view>
#endif
```

But I'd question the value, given there are feature test macros.

**Comment by miscco** [comment] 2022-01-25 11:10
`__has_include` is just a terrible thack. Yeah we have the include because we support later standard modes. So the question that you are posing is the wrong one.

@AlexGuteniev has the right suggestion, although I believe it should be sufficient to just do 
```cpp
#ifdef __cpp_lib_string_view
#include<string_view>
#endif
```

And lets the library figure out whether its supported. If that gives the wrong answer then this is indeed a bug

**Comment by viccpp** [comment] 2022-01-25 11:32
> You should prefer
> 
> #if defined(__cpp_lib_string_view) || __cplusplus >= 201703L || defined(_MSVC_LANG) && _MSVC_LANG >= 201703L

Too ugly. And MSVC++ is not the only compiler we use.

> @AlexGuteniev has the right suggestion, although I believe it should be sufficient to just do
>
> #ifdef __cpp_lib_string_view
> #include<string_view>
> #endif

To check `__cpp_lib_string_view` one must first include `<string_view>`. `__has_include` is C++17 feature when `<version>` is C++20.

Anyways the code presented is fully ISO C++-conformant and sufficiently portable.

**Comment by viccpp** [comment] 2022-01-25 11:35
> You should prefer
> 
> #if defined(__cpp_lib_string_view) || __cplusplus >= 201703L || defined(_MSVC_LANG) && _MSVC_LANG >= 201703L

Consider creating guards like this for that `#warning` if it really helps.

**Comment by viccpp** [comment] 2022-01-25 11:52
Solution like

```
cl -D_SILENCE_MEANINGLESS_WARNINGS ...
```

(addition of some magic macro) is not the best but still working solution. It's better than nothing. But GCC (libstdc++) and Clang (libc++) just eat this code without any warnings and everything works as expected.

**Comment by fsb4000** [comment] 2022-01-25 11:58
> But GCC (libstdc++) and Clang (libc++) just eat this code without any warnings

They just don't have such warnings at all. I include `string_view` in C++14 mode and I don't get any warning: 

https://gcc.godbolt.org/z/YTzM1xWxv

**Comment by viccpp** [comment] 2022-01-25 12:05
Exactly!

**Comment by miscco** [comment] 2022-01-25 12:28
Aka, it was a herrendous idea to make `<version>` C++20 only and all compilers support it in earlier modes afaik

**Comment by viccpp** [comment] 2022-01-25 12:53
GCC 7 doesn't have `<version>` but implements C++17

**Comment by sylveon** [comment] 2022-01-25 19:52
GCC 7 isn't supported anymore either :P

> Too ugly. And MSVC++ is not the only compiler we use.

You can simplify this to `#if defined(__cpp_lib_string_view) || __cplusplus >= 201703L` by passing `/Zc:__cplusplus` to MSVC

**Comment by StephanTLavavej** [comment] 2022-01-25 22:42
Thanks for reporting this issue. This behavior is by design - the original intended use of Standard feature-test macros was to use `__has_include(<meow>)`, followed by `#ifdef __cpp_lib_meow`, which meant that including C++17 `<meow>` in C++14 mode shouldn't be a build error. As the C++ community later realized, this usage scenario isn't great (for reasons including, but not limited to, the fact that build systems often want to determine whether features are available without dragging in the entire machinery - e.g. it would be terrible if Boost.Config had to include basically every STL header to sense feature status). That's why `<version>` was added to C++20 and implemented unconditionally in this repo. (Sometimes `<ciso646>` can be an acceptable stand-in for pre-`<version>` toolsets - that was the case for MSVC although I can't say anything definitive about GCC.)

We're closing this as `wontfix` because we don't believe that further improvements can be made to this scenario - replacing the warning message with an `#error` would break builds that are currently compiling successfully (including but not limited to our test harness). Replacing the warning message with silence would lead to a *very* confusing experience for users who intend to use new features but have forgotten (or didn't know) that they need to enable `/std:c++17`, `/std:c++20`, etc. Guarding the warning message with a macro would be another thing to document and configure - we believe there are plenty of ways to avoid this scenario without adding a mechanism to silence the warning.

**Closed by StephanTLavavej** 2022-01-25 22:42 UTC
Labels: enhancement, wontfix
