### ISSUE TITLE
Unsafe vector assignment operations during reallocations

### ISSUE THREAD

**Issue by winner245** [microsoft/STL#5106] opened 2024-11-21 17:45 UTC
## Description

Current implementations of vector assignment operations—including the copy, move, initializer_list-assignment operators, and all overloads of the `assign` functions, as well as the C++23 `assign_range` function—exhibit unsafe behavior during reallocations triggered by assignments. This can result in a corrupted vector where all elements are erased, as demonstrated in this [demo](https://godbolt.org/z/eYYbodb4n).

## Affected Implementations:
- **MSVC-STL**
- **libc++**

The **libstdc++** implementation handles these cases correctly, ensuring safe operations during reallocations.

I plan to submit a PR to address this issue.

**Comment by CaseyCarter** [comment] 2024-11-21 22:22
So this is an enhancement request for `vector` assignment operations to provide the strong exception safety guarantee?

**Comment by winner245** [comment] 2024-11-21 22:28
Yes, exactly! I am requesting an enhancement to ensure strong exception safety guarantees for vector assignment operations, specifically in cases where the assignments trigger reallocations.

**Comment by StephanTLavavej** [comment] 2024-11-21 23:19
This doesn't sound like something we'd accept. See our documented [non-goals](https://github.com/microsoft/STL?tab=readme-ov-file#non-goals):

> Non-goal: Adding non-Standard extensions.

If the Standard requires only the basic EH guarantee for an operation, then if we achieve that, we are conforming. It is *not* "unsafe" to leave the vector in a valid-but-unspecified state (such as being emptied out) after an exception is thrown. User code should not be assuming guarantees stronger than the Standard provides.

Other implementations may choose to provide stronger behavior (and in other situations we do), but when it comes to EH, providing the strong guarantee is typically more expensive or requires atypical code patterns and extra testing, which is why the Standard *doesn't* require the strong EH guarantee in most places. Personally, I believe that the Standard already requires strong EH guarantees way too often in `<vector>`, so I am personally opposed to providing more as an implementation extension.

**Comment by StephanTLavavej** [comment] 2024-11-22 00:07
You're welcome and thanks for understanding! I checked with @CaseyCarter and he agrees that our current behavior is by design, so I'm going to close this issue and linked PR.

**Closed by StephanTLavavej** 2024-11-22 00:07 UTC
Labels: enhancement, invalid

**Comment by frederick-vs-ja** [comment] 2024-11-23 11:46
> Other implementations may choose to provide stronger behavior (and in other situations we do), but when it comes to EH, providing the strong guarantee is typically more expensive or requires atypical code patterns and extra testing, which is why the Standard _doesn't_ require the strong EH guarantee in most places.

I think the expected changes is just reordering deleting old contents after constructing new contents, which looks quite reasonable to me. Although the peak memory would be higher presumably.

**Comment by winner245** [comment] 2024-11-23 14:04
> >Other implementations may choose to provide stronger behavior (and in other situations we do), but when it comes to EH, providing the strong guarantee is typically more expensive or requires atypical code patterns and extra testing, which is why the Standard doesn't require the strong EH guarantee in most places.
> 
> I think the expected changes is just reordering deleting old contents after constructing new contents, which looks quite reasonable to me. Although the peak memory use would be higher presumably.

Thank you for your feedback and insights. Yes, the proposed change in this issue and related PR #5107 involves nothing but reordering the deletion of old contents after constructing new contents, without requiring additional operations. It's true that the peak memory use would be higher, similar to the case with `push_back` and `emplace_back`. I appreciate your consideration and support. As I mentioned, I respect the decision made and will ensure my future submissions align with the goals of MSVC.
