### ISSUE TITLE
atomic.cpp: Spinlock powering shared_ptr atomics can lead to priority inversion

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#370] opened 2019-12-11 01:24 UTC
**Describe the bug**
shared_ptr's atomic functions (e.g. `std::atomic_store`) are powered by an external lock present in our separately compiled machinery, `_Lock_shared_ptr_spin_lock` and `_Unlock_shared_ptr_spin_lock`. This was written to use a plain spin lock with no mitigation to go to sleep if spinning is taking too long, nor is there any mitigation for memory bandwidth consumption.

https://github.com/microsoft/STL/blob/aa0a7a3d859ade0f6f1ff13aa4ef74b3d5ce2326/stl/src/atomic.cpp#L13-L34

In single threaded scenarios this is particularly bad when a low priority thread currently holds the spinlock, and a high priority thread spins "effectively forever".

In an ABI breaking release, it would be nice to reuse the low order bit of the reference count control block pointer in the shared_ptr; but even without an ABI breaking release we could do better by replacing the spinlock entirely with something like `SRWLOCK` on Vista and later, implementing exponential backoff, or relying on C++20 `std::atomic` waiting features once we have those implemented.

Also tracked by Developer Community as DevCom-716238 and Microsoft-internal VSO-975564.

**Comment by StephanTLavavej** [comment] 2019-12-11 02:45
I believe you've filed a duplicate of #86. If so, which one do you want to keep?

**Comment by StephanTLavavej** [comment] 2019-12-11 02:47
Also, how can this possibly be fixed without breaking ABI, given that existing object files could be calling `_Lock_shared_ptr_spin_lock()` and expecting that to prevent newer object files from modifying a `shared_ptr`?

**Comment by BillyONeal** [comment] 2019-12-11 02:52
> Also, how can this possibly be fixed without breaking ABI, given that existing object files could be calling `_Lock_shared_ptr_spin_lock()` and expecting that to prevent newer object files from modifying a `shared_ptr`?

This bug is not "make shared_ptr stop using a common spinlock", it is "make common lock shared_ptr uses less bad". If we didn't have to worry about XP I would wholesale replace it with an SRWLOCK.

**Comment by StephanTLavavej** [comment] 2019-12-11 02:57
Ah, changing what the separately compiled functions do. I agree that that would be ABI-safe. Thanks!

**Comment by AlexGuteniev** [comment] 2020-04-12 07:19
I think it can be done in scope of #593 as follows:
```
// SPIN LOCK FOR shared_ptr ATOMIC OPERATIONS
std::atomic<volatile long> _Shared_ptr_flag{};

_CRTIMP2_PURE void __cdecl _Lock_shared_ptr_spin_lock() { // spin until _Shared_ptr_flag successfully set
#ifdef _M_ARM
    while (_InterlockedExchange_acq(&_Shared_ptr_flag._Storage._Value, 1)) {
        _Shared_ptr_flag.wait(1, std::memory_order_acquire);
    }
#else // _M_ARM
    while (_interlockedbittestandset(&_Shared_ptr_flag._Storage._Value, 0)) { // set bit 0
        _Shared_ptr_flag.wait(1, std::memory_order_acquire);
    }
#endif // _M_ARM
}
```

But need to link atomic satellite. Is linking atomic satellite acceptable here?

**Comment by BillyONeal** [comment] 2020-04-12 16:58
@AlexGuteniev: I think it would be better to attempt to detect and use SRWLOCK here since that would engage on more OSes.

**Comment by AlexGuteniev** [comment] 2020-04-12 17:15
But atomic wait in #593  has fallback with locking on SRW lock, so OS support will be there starting Vista.  And SRW lock without checking variable directly has unnecessary API function call overhead. 

And I've already added wait-powering for this spinlock in #593  :-)

**Comment by AlexGuteniev** [comment] 2020-04-12 17:30
(But if you still disagree, I can revert this part)

**Closed** 2020-08-18 01:08 UTC
Labels: bug, performance
