### ISSUE TITLE
Enabling C++20 in Clang 10 rc1 causes compilation errors

### ISSUE THREAD

**Issue by Zingam** [microsoft/STL#480] opened 2020-02-04 17:03 UTC
I created a CMake base project, which enabled C++20 in Clang and tried to compile a simple samples, which included `<concepts>`. I got an warning that `<concepts>` are not supported for Clang. I removed that header but the compilation still failed. The same simple code which included `<iostream>` compiled as C++17.

I have the latest VS2019 preview.

Will STL eventually support Clang/C++20?

**Comment by miscco** [comment] 2020-02-04 17:39
Could you please include the code sample and the generated errors. Otherwise it is impossible to help you.

Generally speaking the STL supports clang9 which will most likely be bumped to clang10 in the near future.

**Comment by Zingam** [comment] 2020-02-04 19:11
I can include a sample later if it is necessary. My uneducated guess is that by enabling C++20 in Clang a code path in STL is unlocked that is incompatible with Clang 10 like <concepts>. Even if I don't include anything related to concepts.  For example the code would be something as simple as:

#include <iostream>
int main()
{
    std::cout << "Hello World!" << std::endl;
}

In my CMake file I also added:

set_target( TARGET project PROPERTY CXX_STANDARD 20);

BTW In that case I was using Visual Studio Code/CMake extension + I have VS2019 16.5 Preview 2.

**Comment by StephanTLavavej** [comment] 2020-02-04 19:27
Yes, we need your *exact* source code, and the *exact* error messages you're seeing.

**Comment by CaseyCarter** [comment] 2020-02-04 19:56
Clang 10 RC1 regressed STL support in C++20 mode due to bugs in Concept and `<=>` support: LLVM-41991, LLVM-44627, and LLVM-44689. We recently applied workarounds for LLVM-41991 and LLVM-44689 in #475, but LLVM-44627 unreasonable to workaround. Notably, LLVM-41991 and LLVM-44627 have been fixed for RC2.

Even if you avoid including `<concepts>` directly, some of the other STL headers include it transitively so you will still likely see the error. Feel free to define `_SILENCE_CLANG_CONCEPTS_MESSAGE` to silence it, but be aware that not everything will work correctly unless you have tip-of-trunk STL and tip-of-`release/10.x` clang.

**Comment by CaseyCarter** [comment] 2020-02-04 20:09
> Will STL eventually support Clang/C++20?

Yes. When RC2 is released we'll be able to remove the workarounds for LLVM-41991 as well as the `_SILENCE_CLANG_CONCEPTS_MESSAGE` `#error`, but we'll need to fully validate before we can proclaim victory. I've done some spot checking here and there and found no more bugs to report, but I haven't made a full validation run.

**Comment by Zingam** [comment] 2020-02-04 21:54
@CaseyCarter Thank you for the information. I think my issue is exactly what you describe. I could post the requested info and sample tomorrow or better wait for Clang 10 RC2 and MSVC 16.5 Preview 3 to retry first. I currently have to use Clang 9 which doesn't seem to have these issues but then MSVC 16.5 Preview 2 broke my SFINAE stuff and some of my templates don't compile currently, which I hope to rewrite with concepts soon.

**Comment by StephanTLavavej** [comment] 2020-02-04 22:47
Note that we expect the STL to be unchanged between VS 2019 16.5 Preview 2 and the production release of VS 2019 16.5. (Preview 2 was "feature complete", after which changes stop flowing automatically. We can port individual high-priority fixes, but we haven't had any such fixes for the STL.)

Depending on when Clang 10 releases and VS 2019 16.6 begins to lock down for release, we may need to port changes for Clang 10 support (as it would be unfortunate for this incompatibility to persist for 16.6 as well).

**Comment by CaseyCarter** [comment] 2020-03-19 23:49
#622 corrected most issues with Clang 10, notably including all regressions vs. Clang 9. There's still some weirdness with the Range algorithms which I haven't run down yet, so I'm keeping this issue open.

**Comment by CaseyCarter** [comment] 2020-04-14 04:17
Closed by #708.

**Closed by CaseyCarter** 2020-04-14 04:17 UTC
Labels: bug
