### ISSUE TITLE
<mutex>: Support thread-safety analysis attributes

### ISSUE THREAD

**Issue by KindDragon** [microsoft/STL#3163] opened 2022-10-19 20:55 UTC
Clang support thread-safety analysis attributes http://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h and MSVC Static Analyser probably too https://docs.microsoft.com/en-us/visualstudio/code-quality/annotating-locking-behavior (I haven't check them)

It would be useful for analysing some thread safety issues

P.S. Abseil also support deadlock detection in debug mode https://abseil.io/docs/cpp/guides/synchronization#deadlock-detection, but this feature is too big to hope of implementing :)

**Comment by NN---** [comment] 2022-10-30 18:42
There is an issue with a simpler case using functions. Probably this should be fixed to make annotations work.
https://developercommunity.visualstudio.com/t/SAL-annotations-does-not-give-C26100-or/10112284

**Comment by KindDragon** [comment] 2022-11-02 21:46
@NN--- It seams some of them works with latest MSVC https://godbolt.org/z/98rrn9YTK

**Comment by StephanTLavavej** [comment] 2024-04-03 21:13
Resolving this issue as a duplicate of the newer #4555 because that issue talks only about Clang and is therefore less confusing (since we've abandoned any attempt to use SAL annotations here).

**Closed by StephanTLavavej** 2024-04-03 21:13 UTC
Labels: duplicate, enhancement
