### ISSUE TITLE
`<list>`: C2440 with `_DEBUG` and `/std:c++20` options produced when an `polymorphic_allocator` used as base class in a derived class with a constructor

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#3640] opened 2023-04-08 07:20 UTC
**Describe the bug**
A code example works with libstdc++ and libc++ and doesn't work with the STL.

```c++
#include <list>
#include <memory_resource>

template <typename T>
class pmr_allocator : public std::pmr::polymorphic_allocator<T> {
   public:
    pmr_allocator(){};
};

int main() {
    std::list<double, pmr_allocator<double>> foo;
}
```

Compiler explorer: https://godbolt.org/z/dW4onEW79

Error message:
```
C:/data/msvc/14.34.31931-Pre/include\list(1045): error C2440: 'static_cast': cannot convert from 'pmr_allocator<_Newfirst>' to 'pmr_allocator<_Newfirst>'
        with
        [
            _Newfirst=std::_List_node<double,void *>
        ]
        and
        [
            _Newfirst=std::_Container_proxy
        ]
C:/data/msvc/14.34.31931-Pre/include\list(1045): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:/data/msvc/14.34.31931-Pre/include\list(1042): note: while compiling class template member function 'std::list<double,pmr_allocator<double>>::~list(void) noexcept'
<source>(11): note: see reference to function template instantiation 'std::list<double,pmr_allocator<double>>::~list(void) noexcept' being compiled
<source>(11): note: see reference to class template instantiation 'std::list<double,pmr_allocator<double>>' being compiled
C:/data/msvc/14.34.31931-Pre/include\list(1045): error C2530: '_Alproxy': references must be initialized
C:/data/msvc/14.34.31931-Pre/include\list(1046): error C3536: '_Alproxy': cannot be used before it is initialized
C:/data/msvc/14.34.31931-Pre/include\list(1046): error C2672: '_Delete_plain_internal': no matching overloaded function found
C:/data/msvc/14.34.31931-Pre/include\xmemory(992): note: could be 'void std::_Delete_plain_internal(_Alloc &,_Alloc::value_type *const ) noexcept'
C:/data/msvc/14.34.31931-Pre/include\list(1046): note: Failed to specialize function template 'void std::_Delete_plain_internal(_Alloc &,_Alloc::value_type *const ) noexcept'
C:/data/msvc/14.34.31931-Pre/include\list(1046): note: With the following template arguments:
C:/data/msvc/14.34.31931-Pre/include\list(1046): note: '_Alloc=int'
```

**Expected behavior**
An user thinks that the code should work.

**STL version**
```
Microsoft Visual Studio Community 2022
    
Version 17.5.0
```

**Additional context**
DevCom-10331521

**Comment by fsb4000** [comment] 2023-04-08 07:35
This code works if I add one more constructor.

```c++
#include <list>
#include <memory_resource>

template <typename T>
class pmr_allocator : public std::pmr::polymorphic_allocator<T> {
   public:
    pmr_allocator(){};

    template <class _Uty>
    pmr_allocator(const pmr_allocator<_Uty>& _That) noexcept
        : std::pmr::polymorphic_allocator<T>{_That} {}
};

int main() { std::list<double, pmr_allocator<double>> foo; }
```
https://godbolt.org/z/9a4sqn6T7

**Comment by frederick-vs-ja** [comment] 2023-04-08 13:06
I do believe this is very similar to, or even a duplicate of #2684.

**Comment by fsb4000** [comment] 2023-04-08 14:19
Ok. I see that you have already added a comment to the Devcom issue.

I agree with you, but I will leave this issue open for now so that one of the maintainers can close both issues at once: this github issue and the Devcom issue.

**Closed** 2023-04-10 21:32 UTC
Labels: invalid
