### ISSUE TITLE
<locale> is killing server performance because of the global lock in glibc

### ISSUE THREAD

**Issue by MaruHyl** [microsoft/STL#2134] opened 2021-08-18 10:07 UTC

**Comment by sylveon** [comment] 2021-08-18 10:12
I don't think the Microsoft STL can do anything about glibc.

**Comment by StephanTLavavej** [comment] 2021-08-18 21:54
This is a duplicate of #1652. Unfortunately, we can't fix this while preserving binary compatibility, so that issue is labeled as `vNext` and will need to wait for an upcoming binary-breaking overhaul (there is no ETA for vNext at this time).

**Closed by StephanTLavavej** 2021-08-18 21:54 UTC
Labels: question
