### ISSUE TITLE
<random>: Cannot save/restore a ranlux48 object in a stream

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/STL#437] opened 2020-01-22 23:15 UTC
**Describe the bug**
It appears that the textual representation of ranlux48 is incorrect

**Command-line test case**
STL version (git commit or Visual Studio version): Visual Studio 2019 version 16.4 (but goes back effectively forever)

```
C:\Users\bion\Desktop>type test.cpp
#include <iostream>
#include <random>
#include <sstream>

template <typename RND> void check(const char *name) {
  RND g1, g2;
  std::cout << std::boolalpha << name << ": " << (g1 == g2);
  std::stringstream s;
  s << g1;
  s >> g1;
  std::cout << " " << (g1 == g2) << std::endl;
}

int main() {
  check<std::ranlux48>("ranlux48");
  check<std::ranlux24>("ranlux24");
  check<std::mt19937>("mt19937");
}

C:\Users\bion\Desktop>cl /EHsc /W4 /WX /std:c++latest /nologo .\test.cpp
test.cpp

C:\Users\bion\Desktop>.\test.exe
ranlux48: true false
ranlux24: true true
mt19937: true true

C:\Users\bion\Desktop>
```

**Expected behavior**
ranlux48: true true 
ranlux24: true true 
mt19937: true true

This issue is a dual of Microsoft-internal VSO-104809 and DevCom-249085

**Comment by StephanTLavavej** [comment] 2020-01-23 00:42
I believe this should be resolved as a duplicate of #442. Observe:
https://github.com/microsoft/STL/blob/2989323bdc47a5e0eac4537a862f8c06f503d6fe/stl/inc/random#L4933
https://github.com/microsoft/STL/blob/2989323bdc47a5e0eac4537a862f8c06f503d6fe/stl/inc/random#L4935

**Closed** 2020-01-23 00:51 UTC
Labels: bug, duplicate
