### ISSUE TITLE
```<filesystem>``` + ```<ranges>```: Cannot reverse path

### ISSUE THREAD

**Issue by nico-engels** [microsoft/STL#3474] opened 2023-02-16 19:21 UTC
**Describe the bug**
Cannot use ```view::reverse``` on a ```filesystem::path```. Apparently not satisfing the concept ```_Can_reverse```, the path iterator is a LegacyBidirectionalIterator, I think it must work. Tried with ```view::all``` and ```view::common```.

**Command-line test case**

https://godbolt.org/z/K6aavqrWx

**Comment by nico-engels** [comment] 2023-02-16 20:32
Maybe the MSVC ```path::iterator``` is not bidirectional. Using ```std::prev```:

``` 
main.cpp
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.35.32213\include\xutility(1241,19): error C2338: static_assert failed: 'prev requires bidirectional iterator' 
main.cpp(57): message : consulte a referência à instanciação '_BidIt std::prev<std::filesystem::path::iterator>(_BidIt
,__int64)' do modelo que está sendo compilada
          with
          [
              _BidIt=std::filesystem::path::iterator
          ]
```

**Comment by MattStephanson** [comment] 2023-02-16 22:17
https://github.com/microsoft/STL/blob/79e80412313b86f9d0f382ad91470292ea2c303c/stl/inc/filesystem#L1388-L1399

**Comment by MattStephanson** [comment] 2023-02-16 22:30
`path` iterators are special because they iterate over the components of the path, not individual characters. This is implemented by having the iterator store its own internal `path` object that contains the current component. Dereferencing the iterator gives a reference to that internal object, not the original `path`. This is a problem with, for example, `std::reverse_iterator<Iter>::operator*`. That is specified to be equivalent to `Iter tmp = current; return *--tmp;`, so you would be returning a reference to a local object that's about to be destroyed.

**Comment by frederick-vs-ja** [comment] 2023-02-17 00:12
There's divergence among implementations, but I think this is permissible. Note that the standard doesn't strictly require `path::iterator` to meet _Cpp17BidirectionalIteraror_ ([[fs.path.itr]/2](https://eel.is/c++draft/fs.path.itr#2)).
- MSVC STL's `path::iterator` merely meets _Cpp17InputIterator_ requirements and only models `input_iterator`.
- libc++'s `path::iterator` merely meets _Cpp17InputIterator_ requirements while modeling `bidirectional_iterator`.
- libstdc++'s `path::iterator` meets _Cpp17BidirectionalIterator_ requirements and models `bidirectional_iterator`.

**Comment by CaseyCarter** [comment] 2023-02-21 14:36
As detailed above, this is not a bug. I'm going to close this issue, but feel free to ask for more clarification.

**Closed by CaseyCarter** 2023-02-21 14:36 UTC

**Comment by frederick-vs-ja** [comment] 2023-02-21 15:26
While this is not a bug, is it worthwhile to change the implementation of `path` in vNext to make it reversible?
