### ISSUE TITLE
exception: exception base should not accept const char*

### ISSUE THREAD

**Issue by Chaosvex** [microsoft/STL#4463] opened 2024-03-10 00:05 UTC
std::exception should not accept a message string argument in its ctor.

# Command-line test case
```
C:\Temp>type repro.cpp
#include <exception>

int main() {
    throw std::exception("Not valid");
}

C:\Temp>cl /EHsc /W4 /WX /std:c++latest .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

repro.cpp
Microsoft (R) Incremental Linker Version 14.36.32535.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:repro.exe
repro.obj
```

# Expected behavior
Program should fail to compile.

# STL version
19.39 (tested in addition to the older repro version).

# Additional context
Minor issue but it'd be one less gotcha when targeting multiple platforms. :)

**Comment by frederick-vs-ja** [comment] 2024-03-10 05:04
Duplicate of #882.

Unfortunately, this is mainly an issue of VCRuntime, and in this repo we can hardly improve anything.

**Comment by Chaosvex** [comment] 2024-03-10 19:02
Thanks for the link, it didn't pop up on my search. I figured it'd likely be a no-fix due to backwards compat. but if it was reported several years ago, it doesn't seem entirely unreasonable that it could have been deprecated back then and then removed when the next language standard switch was added. Bumping up to the next standard in your typical codebase is going to bring with it the expectation that some housekeeping will likely be needed and if you don't want to do that, keep with the current standard you've been using. /std:c++latest makes that implicit but I think it still largely applies.

At the very least, a warning could be used so it doesn't break existing code but does at least let you know that you've likely unintentionally written non-portable code.

**Comment by frederick-vs-ja** [comment] 2024-03-11 02:07
The status quo is very unfortunate. The proper `std::exception` class and its friends are maintained in VCRuntime so we can't improve anything in this repo.

In this repo, only non-standard exception classes in namespace `stdext` are provided instead and pulled into `std` when `_HAS_EXCEPTIONS` is `0`, which doesn't seem conforming. Although it's already non-conforming to opt-out exceptions.

**Closed** 2024-03-13 21:20 UTC
Labels: duplicate
