### ISSUE TITLE
<deque>,<vector>: Template nested use compile error

### ISSUE THREAD

**Issue by 66maer** [microsoft/STL#2945] opened 2022-07-26 06:41 UTC
## Compiling the following scene with Visual Studio 2022, I get a compile error

I used C++17 inline static member variables

file: hello.hpp
``` c++
#pragma once

#include <vector>
#include <deque>

template <typename T>
class MyQue {
    std::deque<T> que_;
};

class A{
    inline static MyQue<A> myque_;
};

```

file hello.cpp
```c++
#include "hello.h"

int main() {
    A a;
}
```

## I found this weird problem with the following scenario

1. compile directly (Everything is the default configuration Debug/x64/C++17)
2. At this time, an error will be reported, an undefined type is used 'A'
3. Change `deque` to `vector`, compile through   ```std::deque<T> que_;``` ----->```std::vector<T> que_;```

I don't understand, why deque doesn't work properly

// in an experiment，If you do not clear the cache at this time and change back to deque, the compilation can still pass.

These codes can be compiled smoothly in linux gcc-9

**Comment by fsb4000** [comment] 2022-07-26 07:46
Partially reduced example:
```c++
#include <deque>
using namespace std;
template <class _Ty, class _Alloc = allocator<_Ty>>
class deque {
private:
    using _Alty = _Rebind_alloc_t<_Alloc, _Ty>;
    using _Alty_traits = allocator_traits<_Alty>;
    using _Alpty = _Rebind_alloc_t<_Alloc, typename _Alty_traits::pointer>;
    using _Alpty_traits = allocator_traits<_Alpty>;
    using _Mapptr = typename _Alpty_traits::pointer;

    using _Scary_val = _Deque_val<conditional_t<_Is_simple_alloc_v<_Alty>, _Deque_simple_types<_Ty>,
        _Deque_iter_types<_Ty, typename _Alty_traits::size_type, typename _Alty_traits::difference_type,
        typename _Alty_traits::pointer, typename _Alty_traits::const_pointer, _Ty&, const _Ty&, _Mapptr>>>;
    static constexpr int _Block_size = _Scary_val::_Block_size;

public:
    deque() = default;
};

template <typename T>
class MyQue {
    ::deque<T> que_;
};

class A {
    inline static MyQue<A> myque_;
};

int main() {
    A a;
    (void)a;
}
```

```
clang-cl /nologo /std:c++17 /EHsc /W4 /WX main.cpp
# works

clang-cl -v
clang version 14.0.5
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\Llvm\x64\bin
```

```
cl /nologo /std:c++17 /EHsc /W4 /WX main.cpp

C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31627\include\deque(558): error C2027: use of undefined type 'A'
main.cpp(26): note: see declaration of 'A'
main.cpp(15): note: see reference to class template instantiation 'std::_Deque_val<std::_Deque_simple_types<_Ty>>' being compiled
        with
        [
            _Ty=A
        ]
main.cpp(23): note: see reference to class template instantiation 'deque<T,std::allocator<_Ty>>' being compiled
        with
        [
            T=A,
            _Ty=A
        ]
main.cpp(27): note: see reference to class template instantiation 'MyQue<A>' being compiled
```

**Comment by fsb4000** [comment] 2022-07-26 15:03
Oh, I remember. This is known and it will be won't fix.
Sorry.
More info: https://github.com/microsoft/STL/pull/2506

**Comment by 66maer** [comment] 2022-07-26 15:03
自动回复：我已经收到您的邮件，谢谢。

**Comment by CaseyCarter** [comment] 2022-07-26 16:21
@fsb400 nailed it, this is a duplicate of #2506. (`A` is not complete when declaring its static member ``myque_`.)

**Closed by CaseyCarter** 2022-07-26 16:21 UTC
Labels: duplicate
