### ISSUE TITLE
string: Throwing basic_string() constructor

### ISSUE THREAD

**Issue by michaelvlach** [microsoft/STL#2667] opened 2022-04-23 11:40 UTC
**Describe the bug**
The `basic_string` empty constructor is declared `noexcept` but internally it can still throw an exception. The code that uses `std::string` is then being flagged by LLVM14 (`bugprone-exception-escape`) as possibly throwing. E.g.
```
struct S
{
    std::string name;
};
```
will get flagged as having possibly throwing constructor. Technically it cannot escape as `abort` would get called because of the `noexcept` specifier but the static analyzer is still right in that the implementation should not be throwing (not just be declared as such).

The issue is that it leaks this to the user code. All structs using `std::string` as member variables get flagged by clang-tidy on Windows. That itself is probably an incorrect behavior of clang-tidy (bug report: https://github.com/llvm/llvm-project/issues/54668).

**Command-line test case**
repro.cpp
```
#include <string>

struct S
{
    std::string name;
};

class C
{
public:
    C() = default;
    C(const C &other) = delete;
    C(C &&other) noexcept
    {
        *this = std::move(other);
    }
    ~C() = default;

    auto operator=(const C&) -> C& = delete;
    auto operator=(C &&other) noexcept -> C&
    {
        if (this != &other)
        {
            this->s = std::move(other.s);
        }
        
        return *this;
    }

private:
    S s;
};
```
The command line:
```
clang-tidy repro.cpp -checks=bugprone-exception-escape -- -std=c++20
```
Result:
```
C:\dev>clang-tidy repro.cpp -checks=bugprone-exception-escape -- -std=c++20
15 warnings generated.
C:\dev\repro.cpp:3:8: warning: an exception may be thrown in function 'S' which should not throw exceptions [bugprone-exception-escape]
struct S
       ^
C:\dev\repro.cpp:3:8: warning: an exception may be thrown in function 'operator=' which should not throw exceptions [bugprone-exception-escape]
C:\dev\repro.cpp:13:5: warning: an exception may be thrown in function 'C' which should not throw exceptions [bugprone-exception-escape]
    C(C &&other) noexcept
    ^
C:\dev\repro.cpp:20:10: warning: an exception may be thrown in function 'operator=' which should not throw exceptions [bugprone-exception-escape]
    auto operator=(C &&other) noexcept -> C&
         ^
Suppressed 11 warnings (11 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
```

**Expected behavior**
No warning detected.

**STL version**
    ```
    Microsoft Visual Studio Community 2022
    Version 17.1.5
    ```

**Additional context**

**Comment by miscco** [comment] 2022-04-23 12:32
This stems from https://github.com/microsoft/STL/blob/bf3ac95af7438f818eac1754c9f16cfdb416cd23/stl/inc/xstring#L2824 so I am not too sure what we can do here

**Comment by michaelvlach** [comment] 2022-04-23 13:41
I do not understand why would the move assignment operator run into OOM? It shouldn't allocate anything I would presume? Or is it that `_Orphan_all()` / `_Reload_proxy()` could allocate (and therefore throw OOM) and since they are used here this gets triggered?

Looking at the `libc++` (https://github.com/llvm/llvm-project/blob/29c8c070a1770fc510ccad3be753f6f50336f8cc/libcxx/include/string#L2450) it seems to be doing something similar (going about the assignment through the allocator) but it is using strictly non-throwing `__move_assign`. Perhaps something similar could exist for this purpose here as well?

**Comment by frederick-vs-ja** [comment] 2022-04-23 15:13
I think this is a duplicate of #1035. Perhaps we cannot fix the bug until a new ABI break version (vNext) is available.

**Comment by miscco** [comment] 2022-04-23 16:13
The issue are non-propagating allocators.

There you need to relocate the sequence even in case of move

**Comment by frederick-vs-ja** [comment] 2022-04-24 02:56
> Or is it that `_Orphan_all()` / `_Reload_proxy()` could allocate (and therefore throw OOM) and since they are used here this gets triggered?

When `_ITERATOR_DEBUG_LEVEL` is not `0`, `_Reload_proxy` (inherited from `_Container_base12`) does allocate memory.

https://github.com/microsoft/STL/blob/bf3ac95af7438f818eac1754c9f16cfdb416cd23/stl/inc/xmemory#L1063-L1070

> The issue are non-propagating allocators.

But the referenced comment appears in the branch for propagating allocators... I'm a bit curious about whether the exising proxy can be reused.

**Comment by StephanTLavavej** [comment] 2022-04-27 21:38
Thanks for the report - this is indeed a duplicate of #1035 and we can't change this (due to binary compatibility). This also indeed appears to be a bug in clang-tidy as the constructor is definitely marked `noexcept`. Altering the code, e.g. adding a function-try-block to explicitly catch exceptions and terminate - would potentially impact codegen and wouldn't be worth the risk.

**Closed by StephanTLavavej** 2022-04-27 21:38 UTC
Labels: bug, duplicate
