### ISSUE TITLE
`<vcruntime_exception.h>`: `std::exception::what` is not marked `noexcept`

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#2089] opened 2021-08-01 05:30 UTC
**Describe the bug**
https://en.cppreference.com/w/cpp/error/exception/what says `virtual const char* what() const noexcept;`
but it is not: 
![изображение](https://user-images.githubusercontent.com/4289847/127760037-2f09d0b3-e3c7-4f19-a22f-573029a9f48b.png)

**test case**
```
C:\Temp>type repro.cpp
#include <exception>
#include <stdio.h>

void myfunc() noexcept {
  try {
    // do work
    throw std::exception("my text");
  }
  catch (const std::exception& err) {
    printf("%s", err.what());
  }
}

int main() noexcept {
  myfunc();
}

Build from IDE:
```
![изображение](https://user-images.githubusercontent.com/4289847/127760159-e6180637-be25-4dc4-a4d4-7e91a01692a5.png)

**Expected behavior**
It should be marked `noexcept` and no warning should be generated.

**STL version**
    ```
    Microsoft Visual Studio Community 2022 Preview
    Version 17.0.0 Preview 2.1
    ```

**Additional context**
DevCom-1491683

P.S. I know that `<vcruntime_exception.h>` is not a part of the repo. But as far as I understood it will be soon. So I decided to create the issue.

**Comment by AlexGuteniev** [comment] 2021-08-03 08:23
Duplicate of #948

**Closed** 2021-08-03 12:28 UTC
