### ISSUE TITLE
<iomanip>: std::get_time asserts with "istreambuf_iterator is not dereferenceable" when format is longer than the stream

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#1071] opened 2020-07-21 17:21 UTC
**Describe the bug**
std::get_time doesn't stop parsing the input stream as soon as a mismatch is found or stream is eof, but continues until the format string is exhausted instead. This provokes a dereference of the input stream iterator even when it is at the eof. In debug builds it raises an assert. In release builds it is silently ignored.

**Command-line test case**
```
#include <sstream>
#include <iomanip>
#include <string>
int main()
{
    std::string s("123");
    std::tm t = {};
    std::istringstream ss(s);
    ss >> std::get_time(&t, "%Y-%m-%d %H:%M:%S");
    if (ss.fail()) {
        return 1;
    }
}
```

**Expected behavior**
Should setstate failbit in the stream instead of the assertion.
![test](https://i.imgur.com/YxcoJpE.png)

**STL version**
Microsoft Visual Studio Community 2019 
Version 16.6.4

**Additional context**
See also:
* DevCom-18311, DevCom-246363, DevCom-362423, and Microsoft-internal VSO-713785 / [AB#713785](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/713785)

**Comment by fsb4000** [comment] 2020-07-21 17:37
Maybe [VSO-713785](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/713785) | [DevCom-362423](https://developercommunity.visualstudio.com/content/problem/362423/meow.html) is also a duplicate of the current issue. I don't see "the attached simple program" but judging by the context, they discuss the same issue...

**Comment by StephanTLavavej** [comment] 2020-07-30 23:20
Yep, that's a duplicate! I'll link them up, thanks. My analysis from VSO-713785:



This is a bug. The problem is in `<xloctime>`:

```cpp
_InIt __CLR_OR_THIS_CALL _Getfmt(_InIt _First, _InIt _Last, ios_base& _Iosbase, ios_base::iostate& _State, tm* _Pt,
    const char* _Fmtfirst) const { // get formatted time for format NTBS
    const _Ctype& _Ctype_fac = _STD use_facet<_Ctype>(_Iosbase.getloc());

    for (; *_Fmtfirst != '\0'; ++_Fmtfirst) {
        if (*_Fmtfirst == '%') {
            _First = do_get(_First, _Last, _Iosbase, _State, _Pt,
                *++_Fmtfirst); // convert a single field
        } else if (*_Fmtfirst == ' ') {
            while (_First != _Last && _Ctype_fac.is(_Ctype::space, *_First)) {
                ++_First;
            }
        } else if (_Ctype_fac.narrow(*_First) != *_Fmtfirst) { // bad literal match
            _State |= ios_base::failbit;
            break;
```

Here, the "bad literal match" codepath assumes that it can dereference `_First`, but we've reached the end of the input (it's looking for hours:minutes:seconds but there are only hours:minutes).

I'm not sure if we should also set `eofbit` when we encounter the end of the input here.

**Comment by Arzaghi** [comment] 2020-09-27 03:18
@StephanTLavavej 
I've just investigated this issue. It seems this issue has been solved automatically with one of my previous [Pull Requests](https://github.com/microsoft/STL/pull/1168). The following lines prevent reproducing this issue anymore. 

https://github.com/microsoft/STL/blob/530bdc5aaa8a21277e1281ad3df8b8d8433b5caa/stl/inc/xloctime#L136-L139

May I just add a test case for this issue?

**Comment by CaseyCarter** [comment] 2020-09-28 20:03
> May I just add some test cases to cover this issue?

Yes, absolutely. If intervening changes have indirectly fixed this bug, the appropriate action is to add a regression test and close it as fixed.

**Comment by Arzaghi** [comment] 2020-09-29 00:46
> I'm not sure if we should also set eofbit when we encounter the end of the input here.

[It seems](https://godbolt.org/z/7zfqG3) Clang and GCC set `eofbit` in this case.

**Comment by Arzaghi** [comment] 2020-09-29 01:20
> I'm not sure if we should also set eofbit when we encounter the end of the input here.

[It seems](https://godbolt.org/z/3TbGf1) Clang and GCC set `eofbit` in this case.

**Closed** 2020-10-05 23:21 UTC
Labels: bug

**Comment by Amaroker** [comment] 2020-10-16 23:01
There are three DevCom issues related to this issue (see "Additional context" above). Shouldn't they be marked fixed as well?

**Comment by CaseyCarter** [comment] 2020-10-17 00:35
> There are three DevCom issues related to this issue (see "Additional context" above). Shouldn't they be marked fixed as well?

Yes they should - good catch. We don't have smart enough automation to close internal bugs when the GH bug is closed, we have to remember to either (1) mark the PR as fixing the internal bug when we port the PR, or (2) mark the internal bug as fixed when we close the GH bug. That little non-automated step is a bit of a stumbling block.

I've closed VSO-713785, which flows automatically to the DevCom bugs - they are "Fixed Pending Release".

**Comment by fsb4000** [comment] 2020-10-17 04:14
@CaseyCarter Maybe related: 
the bug is fixed https://github.com/microsoft/STL/issues/1309
but https://developercommunity.visualstudio.com/content/problem/1190997/meow.html is still "Under Consideration"

**Comment by CaseyCarter** [comment] 2020-10-17 16:36
> @CaseyCarter Maybe related:
> the bug is fixed #1309
> but https://developercommunity.visualstudio.com/content/problem/1190997/meow.html is still "Under Consideration"

It's "Related" in the sense that apparently neither @StephanTLavavej nor I can properly follow the documented procedure at https://github.com/microsoft/STL/wiki/Checklist-For-Merging-A-Pull-Request. I am now highly suspicious that there are more such instances and that I should audit all the closed issues.

**Comment by CaseyCarter** [comment] 2020-10-18 00:39
> I am now highly suspicious that there are more such instances and that I should audit all the closed issues.

I was right to suspect: I found 3-4 more occurrences. Thanks again, @fsb4000!

**Comment by fsb4000** [comment] 2020-10-18 00:41
Great!  You are welcome! @CaseyCarter
