### ISSUE TITLE
<ranges> : std::views::join and std::ranges::join_view  

### ISSUE THREAD

**Issue by piratadelcaribe** [microsoft/STL#2294] opened 2021-10-22 14:13 UTC
**Description**

The following basic example of `std::views::join` does not compile on Visual Studio 2019 (v142) with the latest compiler (enabling c++20 of course) and 10.0 SDK. The same code in [Wandbox](https://wandbox.org/permlink/CwXMrXttPEpQvbnG) runs without any issue.

**Command-line test case**
```
#include <iostream>
#include <vector>
#include <ranges>


auto isEven = [](int x){return x % 2 == 0;};

auto reproduce = [](int x) -> std::vector<int> { return {x,x}; };

int main()
{
    std::vector<int> w = {1,2,3,4,5,6};
    
    auto result = w | std::views::filter(isEven)
                              | std::views::transform(reproduce)
                              | std::views::join;
    
    for (auto& x : result){
        std::cout << " x = " << x << std::endl;
    }
    
}
```

The result should be `{2,2,4,4,6,6}`. I get the following compiler error on Microsoft Visual Studio Professional 2019, Version 16.11.5.

```
no operator "|" matches these operands. 
binary "|": no operator found which takes a left-hand operand of type 'std::ranges::transform_view<std::ranges::filter_view<std::ranges::ref_view<std::vector<int, std::allocator<int>>>, _Ty>, lambda_2>>' (or there is no acceptable conversion)

**Comment by StephanTLavavej** [comment] 2021-10-23 00:24
Thanks for the report! @JMazurkiewicz and @fsb4000 are correct - closing as a duplicate of #1814. Also see https://devblogs.microsoft.com/cppblog/msvc-cpp20-and-the-std-cpp20-switch/ for more info.

**Closed by StephanTLavavej** 2021-10-23 00:24 UTC
Labels: duplicate
